from enum import IntEnum
from typing import Dict, NamedTuple

class AnimalLocationFlag(IntEnum):
    none = 0
    main_path = 1
    side_path = 2
    reasonable = 3
    pain = 4
    never = 99


class ModFlag(IntEnum):
    vanilla = 0
    apotheosis = 1

class AnimalLocation(NamedTuple):
    id: int
    names: list
    regions: list
    flag: AnimalLocationFlag = 99
    ltype = "Kill"
    mod: ModFlag = 0

location_animal_mapping: Dict[str, AnimalLocation] = {
    "player": AnimalLocation(112001, [ "Minä", "Me" ], [ "Forest" ], AnimalLocationFlag.main_path),
    "sheep": AnimalLocation(112002, [ "Lammas", "Sheep" ], [ "Lake" ], AnimalLocationFlag.reasonable),
    "sheep_bat": AnimalLocation(112003, [ "Lentolammas", "Flying Sheep" ], [ "Forest" ], AnimalLocationFlag.reasonable),
    "sheep_fly": AnimalLocation(112004, [ "Suhiseva lammas", "Buzzing Sheep" ], [ "Forest" ], AnimalLocationFlag.reasonable),
    "scorpion": AnimalLocation(112005, [ "Skorpioni", "Scorpion" ], [ "Pyramid", "Temple of the Art", "Watchtower", "Wizards' Den" ], AnimalLocationFlag.main_path),
    "fish": AnimalLocation(112006, [ "Eväkäs", "Fish" ], [ "Forest", "Snowy Depths Holy Mountain", "Lake", "Hiisi Base" ], AnimalLocationFlag.main_path),
    "fish_large": AnimalLocation(112007, [ "Suureväkäs", "Large Fish" ], [ "Lake", "Snowy Depths" ], AnimalLocationFlag.side_path),
    "duck": AnimalLocation(112008, [ "Ankka", "Duck" ], [ "Lake" ], AnimalLocationFlag.reasonable),
    "wolf": AnimalLocation(112009, [ "Susi", "Wolf" ], [ "Lake", "The Tower" ], AnimalLocationFlag.reasonable),
    "deer": AnimalLocation(112010, [ "Nelikoipi", "Deer" ], [ "Lake" ], AnimalLocationFlag.reasonable),
    "elk": AnimalLocation(112011, [ "Poro", "Reindeer" ], [ "Lake" ], AnimalLocationFlag.reasonable),
    "eel": AnimalLocation(112012, [ "Nahkiainen", "Lamprey" ], [ "Lake" ], AnimalLocationFlag.reasonable),
    "zombie_weak": AnimalLocation(112013, [ "Heikkohurtta", "Weak Hound" ], [ "Mines" ], AnimalLocationFlag.main_path),
    "zombie": AnimalLocation(112014, [ "Hurtta", "Hound" ], [ "Collapsed Mines", "Fungal Caverns", "The Tower" ], AnimalLocationFlag.main_path),
    "miner_weak": AnimalLocation(112015, [ "Tappurahiisiläinen", "Weak Hiisi Miner" ], [ "Mines", "Coal Pits" ], AnimalLocationFlag.main_path),
    "miner": AnimalLocation(112016, [ "Tappurahiisi", "Miner Hiisi" ], [ "Collapsed Mines", "Coal Pits", "The Tower" ], AnimalLocationFlag.main_path),
    "miner_fire": AnimalLocation(112017, [ "Tulihiisi", "Fire Hiisi" ], [ "Collapsed Mines", "Coal Pits", "The Tower" ], AnimalLocationFlag.main_path),
    "miner_santa": AnimalLocation(112018, [ "Jouluhiisi", "Christmas Hiisi" ], [ "Mines", "Collapsed Mines", "Coal Pits" ], AnimalLocationFlag.never),
    "miner_chef": AnimalLocation(112019, [ "Kokkihiisi", "Hiisi Chef" ], [ "Hiisi Base" ], AnimalLocationFlag.never),
    "goblin_bomb": AnimalLocation(112020, [ "Sähikäismenninkäinen", "Firecracker Goblin" ], [ "Coal Pits", "The Tower" ], AnimalLocationFlag.main_path),
    "shotgunner_weak": AnimalLocation(112021, [ "Heikko haulikkohiisi", "Weak Shotgun Hiisi" ], [ "Mines" ], AnimalLocationFlag.main_path),
    "shotgunner": AnimalLocation(112022, [ "Haulikkohiisi", "Shotgun Hiisi" ], [ "Mines", "Collapsed Mines", "Coal Pits", "Snowy Depths", "Hiisi Base", "The Tower" ], AnimalLocationFlag.main_path),
    "scavenger_smg": AnimalLocation(112023, [ "Rynkkyhiisi", "Hiisi Gunner" ], [ "Snowy Depths", "Hiisi Base", "Underground Jungle", "The Vault", "Sandcave", "Desert Chasm", "Frozen Vault", "Snowy Chasm", "The Tower" ], AnimalLocationFlag.main_path),
    "scavenger_grenade": AnimalLocation(112024, [ "Kranuhiisi", "Hiisi Grenadier" ], [ "Snowy Depths", "Hiisi Base", "Underground Jungle", "The Vault", "Sandcave", "Desert Chasm", "Frozen Vault", "Snowy Chasm", "The Tower" ], AnimalLocationFlag.main_path),
    "scavenger_mine": AnimalLocation(112025, [ "Miinankylväjä", "Hiisi Mine Thrower" ], [ "Coal Pits", "Snowy Depths", "Hiisi Base", "Underground Jungle", "The Vault", "Sandcave", "Frozen Vault", "The Tower" ], AnimalLocationFlag.main_path),
    "scavenger_heal": AnimalLocation(112026, [ "Parantajahiisi", "Hiisi Healer" ], [ "Hiisi Base", "Underground Jungle", "The Vault", "Sandcave", "Frozen Vault", "The Tower" ], AnimalLocationFlag.main_path),
    "scavenger_glue": AnimalLocation(112027, [ "Liimahiisi", "Glue Hiisi" ], [ "Snowy Depths", "The Vault", "Frozen Vault", "Power Plant" ], AnimalLocationFlag.main_path),
    "scavenger_invis": AnimalLocation(112028, [ "Häivehiisi", "Stealth Hiisi" ], [ "Fungal Caverns", "Frozen Vault", "Sandcave" ], AnimalLocationFlag.main_path),
    "scavenger_shield": AnimalLocation(112029, [ "Kilpihiisi", "Shield Hiisi" ], [ "Fungal Caverns", "Frozen Vault", "The Tower" ], AnimalLocationFlag.side_path),
    "scavenger_poison": AnimalLocation(112030, [ "Myrkkyhiisi", "Hiisi Poisoner" ], [ "Underground Jungle", "Sandcave", "The Tower" ], AnimalLocationFlag.main_path),
    "scavenger_clusterbomb": AnimalLocation(112031, [ "Isohiisi", "Hiisi Bomber" ], [ "Hiisi Base", "Underground Jungle", "Sandcave", "The Tower" ], AnimalLocationFlag.main_path),
    "scavenger_leader": AnimalLocation(112032, [ "Toimari", "Hiisi Leader" ], [ "Snowy Depths", "Hiisi Base", "Underground Jungle", "The Vault", "Frozen Vault", "Sandcave", "Desert Chasm", "The Tower" ], AnimalLocationFlag.main_path),
    "alchemist": AnimalLocation(112033, [ "Puistokemisti", "Hiisi Alchemist" ], [ "Mines", "Coal Pits", "Fungal Caverns", "Pyramid", "Overgrown Cavern", "The Tower" ], AnimalLocationFlag.main_path),
    "sniper": AnimalLocation(112034, [ "Snipuhiisi", "Hiisi Sniper" ], [ "Snowy Depths", "Hiisi Base", "The Vault", "The Tower" ], AnimalLocationFlag.main_path),
    "shaman": AnimalLocation(112035, [ "Märkiäinen", "Swampling" ], [ "Mines", "Collapsed Mines", "Underground Jungle" ], AnimalLocationFlag.main_path),
    "coward": AnimalLocation(112036, [ "Raukka", "Coward" ], [ "Hiisi Base", "Underground Jungle", "The Vault", "Frozen Vault", "The Tower" ], AnimalLocationFlag.main_path),
    "flamer": AnimalLocation(112037, [ "Liekkari", "Flamer" ], [ "Underground Jungle", "The Vault", "The Tower" ], AnimalLocationFlag.main_path),
    "icer": AnimalLocation(112038, [ "Jäähdytyslaite", "Icer" ], [ "The Vault", "Frozen Vault", "The Tower" ], AnimalLocationFlag.main_path),
    "bigzombie": AnimalLocation(112039, [ "Mätänevä ruumis", "Rotting Corpse" ], [ "The Vault", "Frozen Vault", "Fungal Caverns", "The Tower" ], AnimalLocationFlag.main_path),
    "bigzombietorso": AnimalLocation(112040, [ "Mätänevä kroppa", "Rotting Body" ], [ "The Vault", "Frozen Vault", "Fungal Caverns", "The Tower" ], AnimalLocationFlag.main_path),
    "bigzombiehead": AnimalLocation(112041, [ "Mätänevä pää", "Rotting Head" ], [ "The Vault", "Frozen Vault", "Fungal Caverns", "The Tower" ], AnimalLocationFlag.main_path),
    "slimeshooter_weak": AnimalLocation(112042, [ "Heikko limanuljaska", "Weak Toxic Slime" ], [ "Mines" ], AnimalLocationFlag.main_path),
    "slimeshooter": AnimalLocation(112043, [ "Limanuljaska", "Toxic Slime" ], [ "Coal Pits", "Fungal Caverns", "Snowy Depths", "The Tower" ], AnimalLocationFlag.main_path),
    "acidshooter_weak": AnimalLocation(112044, [ "Heikko happonuljaska", "Weak Acid Slime" ], [ "Mines" ], AnimalLocationFlag.main_path),
    "acidshooter": AnimalLocation(112045, [ "Happonuljaska", "Acid Slime" ], [ "Mines", "Fungal Caverns", "The Vault", "Temple of the Art", "Frozen Vault", "The Tower" ], AnimalLocationFlag.main_path),
    "lasershooter": AnimalLocation(112046, [ "Mulkkio", "Gazer" ], [ "The Vault", "Frozen Vault", "Temple of the Art", "The Tower" ], AnimalLocationFlag.main_path),
    "giantshooter_weak": AnimalLocation(112047, [ "Heikko äitinuljaska", "Weak Mother Slime" ], [ "Mines" ], AnimalLocationFlag.main_path),
    "giantshooter": AnimalLocation(112048, [ "Äitinuljaska", "Mother Slime" ], [ "Mines", "Fungal Caverns", "The Tower" ], AnimalLocationFlag.main_path),
    "miniblob": AnimalLocation(112049, [ "Möykky", "Blob" ], [ "Fungal Caverns", "Overgrown Cavern", "The Vault", "Frozen Vault", "The Tower" ], AnimalLocationFlag.main_path),
    "blob": AnimalLocation(112050, [ "Kiukkumöykky", "Angry Blob" ], [ "Fungal Caverns", "Overgrown Cavern", "The Vault", "Frozen Vault", "The Tower" ], AnimalLocationFlag.main_path),
    "ant": AnimalLocation(112051, [ "Murkku", "Ant" ], [ "Fungal Caverns", "Overgrown Cavern", "The Tower" ], AnimalLocationFlag.side_path),
    "rat": AnimalLocation(112052, [ "Rotta", "Rat" ], [ "Mines", "Coal Pits", "Fungal Caverns", "Snowy Depths", "Hiisi Base", "Meat Realm", "The Tower" ], AnimalLocationFlag.main_path),
    "bat": AnimalLocation(112053, [ "Lepakko", "Bat" ], [ "Coal Pits", "The Tower" ], AnimalLocationFlag.main_path),
    "bigbat": AnimalLocation(112054, [ "Suurlepakko", "Large Bat" ], [ "Coal Pits", "The Tower" ], AnimalLocationFlag.main_path),
    "firebug": AnimalLocation(112055, [ "Pikkutulikärpänen", "Lesser firefly" ], [ "Coal Pits", "The Tower" ], AnimalLocationFlag.main_path),
    "bigfirebug": AnimalLocation(112056, [ "Suurtulikärpänen", "Greater firefly" ], [ "Coal Pits", "The Tower" ], AnimalLocationFlag.main_path),
    "bloom": AnimalLocation(112057, [ "Puska", "Bloom" ], [ "Underground Jungle", "The Tower" ], AnimalLocationFlag.main_path),
    "shooterflower": AnimalLocation(112058, [ "Plasmakukka", "Plasma Flower" ], [ "Underground Jungle", "The Tower" ], AnimalLocationFlag.main_path),
    "fly": AnimalLocation(112059, [ "Amppari", "Wasp" ], [ "Underground Jungle", "Fungal Caverns", "The Tower" ], AnimalLocationFlag.main_path),
    "frog": AnimalLocation(112060, [ "Konna", "Toad" ], [ "Collapsed Mines", "Fungal Caverns", "The Tower" ], AnimalLocationFlag.side_path),
    "frog_big": AnimalLocation(112061, [ "Jättikonna", "Big Toad" ], [ "Collapsed Mines", "Fungal Caverns", "Overgrown Cavern", "The Tower" ], AnimalLocationFlag.side_path),
    "fungus": AnimalLocation(112062, [ "Laahustussieni", "Shuffling Fungus" ], [ "Mines", "Fungal Caverns", "Overgrown Cavern", "Underground Jungle", "The Tower", "Lukki Lair" ], AnimalLocationFlag.main_path),
    "fungus_big": AnimalLocation(112063, [ "Nuijamalikka", "Club-foot" ], [ "Fungal Caverns", "Overgrown Cavern", "Mines", "The Tower", "Lukki Lair" ], AnimalLocationFlag.side_path),
    "fungus_giga": AnimalLocation(112064, [ "Huhtasieni", "Pollen Morel" ], [ "Overgrown Cavern", "The Tower" ], AnimalLocationFlag.side_path),
    "lurker": AnimalLocation(112065, [ "Varjokupla", "Shadow Bubble" ], [ "Lukki Lair" ], AnimalLocationFlag.reasonable),
    "maggot": AnimalLocation(112066, [ "Toukka", "Maggot" ], [ "Underground Jungle", "Fungal Caverns", "The Vault", "Temple of the Art", "The Tower" ], AnimalLocationFlag.main_path),
    "skullrat": AnimalLocation(112067, [ "Kallorotta", "Skull Rat" ], [ "Pyramid", "Temple of the Art", "The Tower" ], AnimalLocationFlag.main_path),
    "skullfly": AnimalLocation(112068, [ "Kallokärpänen", "Skull Fly" ], [ "Pyramid", "Temple of the Art", "The Tower" ], AnimalLocationFlag.main_path),
    "tentacler_small": AnimalLocation(112069, [ "Pikkuturso", "Small Tentacler" ], [ "Fungal Caverns", "Temple of the Art", "The Tower" ], AnimalLocationFlag.main_path),
    "tentacler": AnimalLocation(112070, [ "Turso", "Tentacler" ], [ "Fungal Caverns", "The Vault", "Temple of the Art", "The Tower" ], AnimalLocationFlag.main_path),
    "ghoul": AnimalLocation(112071, [ "Sylkyri", "Spitter" ], [ "The Tower" ], AnimalLocationFlag.pain),
    "giant": AnimalLocation(112072, [ "Hiidenkivi", "Rock Giant" ], [ "Snowy Depths", "The Tower" ], AnimalLocationFlag.main_path),
    "pebble": AnimalLocation(112073, [ "Lohkare", "Rock Spirit" ], [ "Snowy Depths", "The Tower" ] ),
    "longleg": AnimalLocation(112074, [ "Hämis", "Spidey" ], [ "Mines", "Collapsed Mines", "Pyramid", "Temple of the Art", "The Tower" ], AnimalLocationFlag.main_path),
    "lukki_tiny": AnimalLocation(112075, [ "Pikkuhämähäkki", "Small Spider" ], [ "Underground Jungle" ], AnimalLocationFlag.main_path),
    "lukki": AnimalLocation(112076, [ "Hämähäkki", "Spider" ], [ "Underground Jungle", "Lukki Lair" ], AnimalLocationFlag.main_path),
    "lukki_longleg": AnimalLocation(112077, [ "Lukki", "Daddy Longlegs" ], [ "Underground Jungle" ], AnimalLocationFlag.main_path),
    "lukki_creepy_long": AnimalLocation(112078, [ "Kasvoton Lukki", "Faceless spider" ], [ "Lukki Lair" ], AnimalLocationFlag.reasonable),
    "lukki_dark": AnimalLocation(112079, [ "Kammolukki", "Toothy spider" ], [ "Lukki Lair" ], AnimalLocationFlag.reasonable),
    "worm_tiny": AnimalLocation(112080, [ "Pikkumato", "Small Worm" ], [ "Snowy Depths" ], AnimalLocationFlag.reasonable),
    "worm": AnimalLocation(112081, [ "Mato", "Worm" ], [ "Mines", "Collapsed Mines", "Snowy Depths", "Underground Jungle", "Temple of the Art", "Meat Realm" ], AnimalLocationFlag.main_path),
    "worm_big": AnimalLocation(112082, [ "Jättimato", "Giant Worm" ], [ "Mines", "Collapsed Mines", "Coal Pits", "Fungal Caverns", "Snowy Depths", "Underground Jungle", "Meat Realm" ], AnimalLocationFlag.reasonable),
    "worm_skull": AnimalLocation(112083, [ "Kalmamato", "Death Worm" ], [ "Temple of the Art", "The Work (Sky)" ], AnimalLocationFlag.main_path),
    "worm_end": AnimalLocation(112084, [ "Helvetinmato", "Hell Worm" ], [ "The Work (Hell)" ], AnimalLocationFlag.pain),
    "drone_physics": AnimalLocation(112085, [ "Lennokki", "Drone" ], [ "Fungal Caverns", "The Vault", "Frozen Vault", "The Tower" ], AnimalLocationFlag.main_path),
    "drone_lasership": AnimalLocation(112086, [ "Jättilaser-lennokki", "Giant Laser-Drone" ], [ "Hiisi Base", "The Vault", "Frozen Vault", "Power Plant" ], AnimalLocationFlag.main_path),
    "drone_shield": AnimalLocation(112087, [ "Turvalennokki", "Safety Drone" ], [ "Frozen Vault", "The Tower", "Power Plant", "Lukki Lair" ], AnimalLocationFlag.side_path),
    "basebot_sentry": AnimalLocation(112088, [ "Tarkkailija", "Observer" ], [ "Power Plant" ], AnimalLocationFlag.pain),
    "basebot_hidden": AnimalLocation(112089, [ "Vakoilija", "Spy" ], [ "Power Plant" ], AnimalLocationFlag.pain),
    "basebot_neutralizer": AnimalLocation(112090, [ "Pysäyttäjä", "Stopper" ], [ "Power Plant" ], AnimalLocationFlag.pain),
    "basebot_soldier": AnimalLocation(112091, [ "Teloittaja", "Executioner" ], [ "Power Plant" ], AnimalLocationFlag.pain),
    "healerdrone_physics": AnimalLocation(112092, [ "Korjauslennokki", "Repair Drone" ], [ "The Vault", "Frozen Vault", "Power Plant", "The Tower" ], AnimalLocationFlag.reasonable),
    "roboguard": AnimalLocation(112093, [ "Robottikyttä", "Robo-Cop" ], [ "Fungal Caverns", "The Vault", "Frozen Vault", "The Tower" ], AnimalLocationFlag.main_path),
    "roboguard_big": AnimalLocation(112094, [ "Kyrmyniska", "Hunchback" ], [ "Power Plant" ], AnimalLocationFlag.pain),
    "assassin": AnimalLocation(112095, [ "Salamurhaajarobotti", "Assassin Robot" ], [ "The Vault", "Frozen Vault", "Fungal Caverns", "The Tower" ], AnimalLocationFlag.main_path),
    "spearbot": AnimalLocation(112096, [ "Peitsivartija", "Lance Sentry" ], [ "Underground Jungle", "The Vault", "Frozen Vault", "The Sky", "The Work (Sky)", "The Tower" ], AnimalLocationFlag.main_path),
    "tank": AnimalLocation(112097, [ "KK-Tankki", "Tank" ], [ "Snowy Depths", "Hiisi Base", "The Vault", "Frozen Vault", "Desert Chasm", "Snowy Chasm", "The Tower" ], AnimalLocationFlag.main_path),
    "tank_rocket": AnimalLocation(112098, [ "IT-Tankki", "Rocket Tank" ], [ "Snowy Depths", "Hiisi Base", "Sandcave", "Frozen Vault", "The Tower" ], AnimalLocationFlag.main_path),
    "tank_super": AnimalLocation(112099, [ "Laser-Tankki", "Laser Tank" ], [ "Snowy Depths", "Hiisi Base", "The Vault", "Frozen Vault", "Power Plant", "The Tower" ], AnimalLocationFlag.main_path),
    "turret_left": AnimalLocation(112100, [ "Torjuntalaite", "Turret" ], [ "Hiisi Base", "The Vault", "Frozen Vault", "Power Plant", "The Tower" ], AnimalLocationFlag.never),
    "turret_right": AnimalLocation(112101, [ "Torjuntalaite", "Turret" ], [ "Hiisi Base", "The Vault", "Frozen Vault", "Power Plant", "The Tower" ], AnimalLocationFlag.main_path),
    "monk": AnimalLocation(112102, [ "Munkki", "Monk" ], [ "Snowy Depths", "Underground Jungle", "The Vault", "The Tower" ], AnimalLocationFlag.main_path),
    "missilecrab": AnimalLocation(112103, [ "Heinäsirkka", "Cricket" ], [ "The Vault", "Frozen Vault", "The Tower" ], AnimalLocationFlag.main_path),
    "necrobot": AnimalLocation(112104, [ "Tuonelankone", "Necrobot" ], [ "Frozen Vault", "The Tower", "Power Plant", "Meat Realm" ], AnimalLocationFlag.reasonable),
    "necrobot_super": AnimalLocation(112105, [ "Marraskone", "Super Necrobot" ], [ "Frozen Vault", "Power Plant", "Meat Realm" ], AnimalLocationFlag.pain),
    "fireskull": AnimalLocation(112106, [ "Liekkiö", "Fire Spirit" ], [ "Mines", "Coal Pits", "The Tower" ], AnimalLocationFlag.main_path),
    "iceskull": AnimalLocation(112107, [ "Jäätiö", "Ice Spirit" ], [ "Snowy Depths", "Snowy Chasm", "The Tower" ], AnimalLocationFlag.main_path),
    "thunderskull": AnimalLocation(112108, [ "Sähkiö", "Thunder Spirit" ], [ "Pyramid", "Snowy Depths", "Underground Jungle", "The Vault", "Snowy Chasm", "The Work (Hell)", "The Work (Sky)", "The Tower" ], AnimalLocationFlag.main_path),
    "firemage_weak": AnimalLocation(112109, [ "Stendari", "Fire Mage" ], [ "Mines", "Collapsed Mines", "Desert Chasm" ], AnimalLocationFlag.main_path),
    "firemage": AnimalLocation(112110, [ "Eldari", "Hellfire Mage" ], [ "Fungal Caverns", "The Vault", "Wizards' Den", "Frozen Vault", "Desert Chasm", "The Tower" ], AnimalLocationFlag.main_path),
    "icemage": AnimalLocation(112111, [ "Pakkasukko", "Old Man Winter" ], [ "Snowy Depths", "Frozen Vault", "Wizards' Den", "Snowy Chasm", "Snowy Wasteland", "The Tower" ], AnimalLocationFlag.main_path),
    "thundermage": AnimalLocation(112112, [ "Ukko", "Thunder Mage" ], [ "Fungal Caverns", "Snowy Depths", "The Vault", "Frozen Vault", "Wizards' Den", "The Sky", "Snowy Chasm", "Mines", "Desert Chasm", "The Tower" ], AnimalLocationFlag.main_path),
    "thundermage_big": AnimalLocation(112113, [ "Suur-Ukko", "Great Thunder Mage" ], [ "The Sky", "The Work (Sky)", "Pyramid", "Frozen Vault", "Snowy Chasm", "The Tower" ], AnimalLocationFlag.reasonable),
    "barfer": AnimalLocation(112114, [ "Turvonnu velho", "Bloated Wizard" ], [ "Temple of the Art", "Wizards' Den", "The Tower" ], AnimalLocationFlag.main_path),
    "wizard_dark": AnimalLocation(112115, [ "Sokaisunmestari", "Master of Blinding" ], [ "Fungal Caverns", "Snowy Depths", "The Vault", "Temple of the Art", "Wizards' Den", "Desert Chasm", "The Tower", "Lukki Lair" ], AnimalLocationFlag.main_path),
    "wizard_tele": AnimalLocation(112116, [ "Siirtäjämestari", "Master of Teleportation" ], [ "Fungal Caverns", "Snowy Depths", "Temple of the Art", "Wizards' Den", "The Work (Sky)", "The Sky", "Desert Chasm", "The Tower" ], AnimalLocationFlag.main_path),
    "wizard_poly": AnimalLocation(112117, [ "Muodonmuutosmestari", "Master of Polymorphing" ], [ "Fungal Caverns", "Temple of the Art", "Wizards' Den", "The Tower" ], AnimalLocationFlag.reasonable),
    "wizard_swapper": AnimalLocation(112118, [ "Vaihdosmestari", "Master of Exchange" ], [ "Fungal Caverns", "Snowy Depths", "Temple of the Art", "Wizards' Den", "The Sky", "The Tower" ], AnimalLocationFlag.main_path),
    "wizard_neutral": AnimalLocation(112119, [ "Maadoittajamestari", "Master of Grounding" ], [ "Ancient Laboratory", "Magical Temple", "The Vault", "Temple of the Art", "Pyramid", "Wizards' Den", "Snowy Depths", "The Tower" ], AnimalLocationFlag.main_path),
    "wizard_returner": AnimalLocation(112120, [ "Palauttajamestari", "Master of Returning" ], [ "Ancient Laboratory", "Magical Temple", "Temple of the Art", "Wizards' Den", "Desert Chasm", "The Tower" ], AnimalLocationFlag.main_path),
    "wizard_hearty": AnimalLocation(112121, [ "Haavoittajamestari", "Master of Wounding" ], [ "Underground Jungle", "Magical Temple", "The Vault", "Temple of the Art", "The Tower", "Pyramid", "Frozen Vault", "Wizards' Den", "Meat Realm", "Lukki Lair" ], AnimalLocationFlag.main_path),
    "wizard_homing": AnimalLocation(112122, [ "Kohdennusmestari", "Master of Homing" ], [ "The Tower", "Wizards' Den", "Lukki Lair" ], AnimalLocationFlag.side_path),
    "wizard_weaken": AnimalLocation(112123, [ "Turvattomuusmestari", "Master of Vulnerability" ], [ "Desert Chasm", "The Tower", "Pyramid", "Frozen Vault", "The Sky", "Wizards' Den", "Lukki Lair" ], AnimalLocationFlag.side_path),
    "wizard_twitchy": AnimalLocation(112124, [ "Sätkymestari", "Master of Twitching" ], [ "Fungal Caverns", "Underground Jungle", "Magical Temple", "The Vault", "Temple of the Art", "Pyramid", "Wizards' Den", "The Tower", "Lukki Lair" ], AnimalLocationFlag.main_path),
    "enlightened_alchemist": AnimalLocation(112125, [ "Valaistunut alkemisti", "Enlightened Alchemist" ], [ "Ancient Laboratory", "Magical Temple", "Temple of the Art", "Desert Chasm", "The Tower" ], AnimalLocationFlag.main_path),
    "failed_alchemist": AnimalLocation(112126, [ "Kadotettu alkemisti", "Damned Alchemist" ], [ "Ancient Laboratory", "Magical Temple", "Temple of the Art", "Wizards' Den", "Meat Realm", "The Tower" ], AnimalLocationFlag.main_path),
    "failed_alchemist_b": AnimalLocation(112127, [ "Epäalkemisti", "Non-alchemist" ], [ "Ancient Laboratory", "Magical Temple", "Temple of the Art", "The Tower" ], AnimalLocationFlag.main_path),
    "wraith": AnimalLocation(112128, [ "Hyypiö", "Creep" ], [ "Temple of the Art", "The Tower", "The Work (Hell)", "The Sky" ], AnimalLocationFlag.main_path),
    "wraith_storm": AnimalLocation(112129, [ "Ukkoshyypiö", "Thunder Creep" ], [ "The Tower", "The Sky", "The Work (Sky)" ], AnimalLocationFlag.pain),
    "wraith_glowing": AnimalLocation(112130, [ "Hohtava hyypiö", "Glowing Creep" ], [ "Magical Temple", "Temple of the Art", "The Sky", "The Work (Hell)", "The Tower", "The Work (Sky)" ], AnimalLocationFlag.main_path),
    "statue": AnimalLocation(112131, [ "Patsas", "Statue" ], [ "Ancient Laboratory", "The Tower" ], AnimalLocationFlag.side_path),
    "statue_physics": AnimalLocation(112132, [ "Hohtonaamio", "Glowing Mask" ], [ "Magical Temple", "The Tower" ], AnimalLocationFlag.main_path),
    "snowcrystal": AnimalLocation(112133, [ "Haamukivi", "Ghost Crystal" ], [ "Snowy Chasm", "The Tower" ], AnimalLocationFlag.reasonable),
    "hpcrystal": AnimalLocation(112134, [ "Elvytyskristalli", "Recovery Crystal" ], [ "Snowy Chasm", "Desert Chasm", "The Tower" ], AnimalLocationFlag.reasonable),
    "ghost": AnimalLocation(112135, [ "Houre", "Delirium" ], [ "Temple of the Art", "Wizards' Den", "Snowy Chasm" ], AnimalLocationFlag.main_path),
    "wand_ghost": AnimalLocation(112136, [ "Taikasauva", "Magic Wand" ], [ "Magical Temple" ], AnimalLocationFlag.side_path),
    "ethereal_being": AnimalLocation(112137, [ "Olematon", "Non-existent" ], [ "Snowy Chasm", "Pyramid" ], AnimalLocationFlag.reasonable),
    "playerghost": AnimalLocation(112138, [ "Kummitus", "Ghost" ], [ "Mines", "Collapsed Mines", "Coal Pits", "Fungal Caverns", "Snowy Depths", "Underground Jungle", "The Vault", "Temple of the Art", "Frozen Vault", "Lukki Lair", "Wizards' Den", "Overgrown Cavern", "Power Plant" ], AnimalLocationFlag.never),
    "phantom_a": AnimalLocation(112139, [ "Spiraalikalma", "Spiral Phantom" ], [ "Pyramid", "Magical Temple", "Temple of the Art", "Snowy Chasm", "The Tower" ], AnimalLocationFlag.side_path),
    "phantom_b": AnimalLocation(112140, [ "Kiukkukalma", "Angry Phantom" ], [ "Pyramid", "Magical Temple", "Temple of the Art", "Snowy Chasm", "The Tower" ], AnimalLocationFlag.side_path),
    "confusespirit": AnimalLocation(112141, [ "Utu-Aave", "Fog Spirit" ], [ "Fungal Caverns", "Overgrown Cavern", "Pyramid" ], AnimalLocationFlag.reasonable),
    "berserkspirit": AnimalLocation(112142, [ "Viha-Aave", "Anger Spirit" ], [ "Overgrown Cavern", "Pyramid" ], AnimalLocationFlag.reasonable),
    "weakspirit": AnimalLocation(112143, [ "Kaamo-Aave", "Depression Spirit" ], [ "Pyramid" ], AnimalLocationFlag.reasonable),
    "slimespirit": AnimalLocation(112144, [ "Neva-Aave", "Bog Spirit" ], [ "Coal Pits", "Fungal Caverns", "Meat Realm" ], AnimalLocationFlag.reasonable),
    "necromancer": AnimalLocation(112145, [ "Hahmonvaihtaja", "Shapechanger" ], [ "Magical Temple", "Temple of the Art", "Snowy Depths", "The Tower" ], AnimalLocationFlag.main_path),
    "gazer": AnimalLocation(112146, [ "Helvetinkatse", "Hell Gazer" ], [ "The Work (Hell)", "The Tower" ], AnimalLocationFlag.pain),
    "skygazer": AnimalLocation(112147, [ "Taivaankatse", "Sky Gazer" ], [ "The Work (Sky)" ], AnimalLocationFlag.pain),
    "spitmonster": AnimalLocation(112148, [ "Helvetin sylkijä", "Hell Spitter" ], [ "The Work (Hell)", "The Tower" ], AnimalLocationFlag.pain),
    "crystal_physics": AnimalLocation(112149, [ "Kirottu kristalli", "Cursed Crystal" ], [ "Temple of the Art", "The Tower" ], AnimalLocationFlag.main_path),
    "bloodcrystal_physics": AnimalLocation(112150, [ "Verikristalli", "Blood Crystal" ], [ "The Work (Hell)", "Meat Realm", "The Tower" ], AnimalLocationFlag.pain),
    "skycrystal_physics": AnimalLocation(112151, [ "Taivaskristalli", "Celestial Crystal" ], [ "The Tower", "The Sky", "The Work (Sky)" ], AnimalLocationFlag.pain),
    "chest_mimic": AnimalLocation(112152, [ "Matkija", "Mimic" ], [ "The Sky" ], AnimalLocationFlag.pain),
    "chest_leggy": AnimalLocation(112153, [ "Jalkamatkatavara", "Leggy Mimic" ], [ "The Sky" ], AnimalLocationFlag.never),
    "miner_hell": AnimalLocation(112154, [ "Hornantappurahiisi", "Hell Miner Hiisi" ], [ "Meat Realm" ], AnimalLocationFlag.pain),
    "shotgunner_hell": AnimalLocation(112155, [ "Hornahiisi", "Hell Shotgun Hiisi" ], [ "Meat Realm" ], AnimalLocationFlag.pain),
    "sniper_hell": AnimalLocation(112156, [ "Hornasnipuhiisi", "Hiisi Hell Sniper" ], [ "Meat Realm" ], AnimalLocationFlag.pain),
    "dark_alchemist": AnimalLocation(112157, [ "Pahan muisto", "Memory of Evil" ], [ "The Sky" ], AnimalLocationFlag.never),
    "shaman_wind": AnimalLocation(112158, [ "Valhe", "Lie" ], [ "The Sky" ], AnimalLocationFlag.never),
    "necromancer_shop": AnimalLocation(112159, [ "Stevari", "Guard" ], [ "Snowy Depths", "The Tower" ], AnimalLocationFlag.reasonable),
    "necromancer_super": AnimalLocation(112160, [ "Skoude", "Cop" ], [ "Snowy Depths", "The Tower" ], AnimalLocationFlag.reasonable),
    "boss_dragon": AnimalLocation(112161, [ "Suomuhauki", "Dragon" ], [ "Underground Jungle" ], AnimalLocationFlag.never ),
    "boss_limbs": AnimalLocation(112162, [ "Kolmisilmän Koipi", "Three-Eye's Legs" ], [ "Pyramid" ], AnimalLocationFlag.never ),
    "boss_meat": AnimalLocation(112163, [ "Kolmisilmän sydän", "Three-Eye's Heart" ], [ "Meat Realm" ], AnimalLocationFlag.never ),
    "boss_alchemist": AnimalLocation(112164, [ "Ylialkemisti", "High Alchemist" ], [ "Ancient Laboratory" ], AnimalLocationFlag.never ),
    "parallel_alchemist": AnimalLocation(112165, [ "Alkemistin Varjo", "Alchemist's Shadow" ], [ "Parallel Worlds" ], AnimalLocationFlag.pain ),
    "boss_ghost": AnimalLocation(112166, [ "Unohdettu", "Forgotten" ], [ "Snowy Chasm" ], AnimalLocationFlag.never ),
    "boss_ghost_polyp": AnimalLocation(112167, [ "Häive", "Fade" ], [ "Snowy Chasm" ], AnimalLocationFlag.never ),
    "islandspirit": AnimalLocation(112168, [ "Tapion vasalli", "Tapio's Vassal" ], [ "Lake" ], AnimalLocationFlag.never ),
    "boss_pit": AnimalLocation(112169, [ "Sauvojen tuntija", "Connoisseur of Wands" ], [ "Abyss Orb Room" ], AnimalLocationFlag.never ),
    "boss_robot": AnimalLocation(112170, [ "Kolmisilmän silmä", "Three-Eye's Eye" ], [ "Power Plant" ], AnimalLocationFlag.never ),
    "fish_giga": AnimalLocation(112171, [ "Syväolento", "Creature of the Deep" ], [ "Lake" ], AnimalLocationFlag.never ),
    "maggot_tiny": AnimalLocation(112172, [ "Limatoukka", "Slime Maggot" ], [ "Meat Realm" ], AnimalLocationFlag.never ),
    "parallel_tentacles": AnimalLocation(112173, [ "Kolmisilmän Kätyri", "Three-eye's Minion" ], [ "Parallel Worlds" ], AnimalLocationFlag.pain ),
    "minipit": AnimalLocation(112174, [ "Pienkätyri", "Tiny Minion" ], [ "Frozen Vault", "The Tower", "Power Plant", "Meat Realm" ], AnimalLocationFlag.pain ),
    "gate_monster_a": AnimalLocation(112175, [ "Veska", "Goalkeeper" ], [ "Temple of the Art" ], AnimalLocationFlag.never ),
    "gate_monster_b": AnimalLocation(112176, [ "Molari", "Goalkeeper" ], [ "Temple of the Art" ], AnimalLocationFlag.never ),
    "gate_monster_c": AnimalLocation(112177, [ "Mokke", "Goalkeeper" ], [ "Temple of the Art" ], AnimalLocationFlag.never ),
    "gate_monster_d": AnimalLocation(112178, [ "Seula", "Sieve" ], [ "Temple of the Art" ] , AnimalLocationFlag.never),
    "boss_wizard": AnimalLocation(112179, [ "Mestarien mestari", "Master of Masters" ], [ "Wizards' Den" ], AnimalLocationFlag.never ),
    "boss_centipede": AnimalLocation(112180, [ "Kolmisilmä", "Three-Eye" ], [ "The Laboratory" ], AnimalLocationFlag.never ),
    "ultimate_killer": AnimalLocation(112181, [ "Kauhuhirviö", "Horror Monster" ], [ "Frozen Vault", "Friend Cave" ], AnimalLocationFlag.never ),
    "friend": AnimalLocation(112182, [ "Toveri", "Friend" ], [ "Friend Cave" ], AnimalLocationFlag.never ),
    "boss_sky": AnimalLocation(112183, [ "Kivi", "Stone" ], [ "The Sky" ], AnimalLocationFlag.never ),
    "darkghost": AnimalLocation(112184, [ "Haamu", "Wraith" ], [ "Forest" ], AnimalLocationFlag.never ),
    "meatmaggot": AnimalLocation(112185, [ "Mätäryömijä", "Putrid Crawler" ], [ "Meat Realm" ], AnimalLocationFlag.pain ),

    ## Prop start
    "crystal_green": AnimalLocation(113001, [ "Green Crystal", "Green Crystal" ], [ "Temple of the Art" ], AnimalLocationFlag.main_path ),
    "crystal_pink": AnimalLocation(113002, [ "Pink Crystal", "Pink Crystal" ], [ "Temple of the Art" ], AnimalLocationFlag.main_path ),
    "crystal_red": AnimalLocation(113003, [ "Red Crystal", "Red Crystal" ], [ "Temple of the Art" ], AnimalLocationFlag.main_path ),
    #"forcefield_generator": AnimalLocation(113004, [ "Forcefield Generator", "Forcefield Generator" ], [ "Hiisi Base" ], AnimalLocationFlag.main_path ),
    #"barrel_unstable": AnimalLocation(113005, [ "Oil Barrel", "Oil Barrel" ], [ "Mines" ], AnimalLocationFlag.main_path ),
    #"barrel_radioactive": AnimalLocation(113006, [ "Toxic Barrel", "Toxic Barrel" ], [ "Mines" ], AnimalLocationFlag.main_path ),
    #"tnt": AnimalLocation(113007, [ "Explosive Box", "Explosive Box" ], [ "Mines" ], AnimalLocationFlag.main_path ),
    #"crate": AnimalLocation(113008, [ "Gunpowder Crate", "Gunpowder Crate" ], [ "Hiisi Base" ], AnimalLocationFlag.main_path ),
    #"pressure_tank": AnimalLocation(113009, [ "Pressure Tank", "Pressure Tank" ], [ "The Vault" ], AnimalLocationFlag.main_path ),
    #"propane_tank": AnimalLocation(113010, [ "Propane Tank", "Propane Tank" ], [ "Snowy Depths" ], AnimalLocationFlag.main_path ),
    #"seamine": AnimalLocation(113011, [ "Sea Mine", "Sea Mine" ], [ "Coal Pits" ], AnimalLocationFlag.main_path ),
    #"apparatus_01": AnimalLocation(113012, [ "Vault Apparatus (Hot)", "Vault Apparatus (Hot)" ], [ "The Vault" ], AnimalLocationFlag.main_path ),
    #"apparatus_02": AnimalLocation(113013, [ "Vault Apparatus (Cold)", "Vault Apparatus (Cold)" ], [ "The Vault" ], AnimalLocationFlag.main_path ),
    #"physics_cocoon": AnimalLocation(113014, [ "Worm Cocoon", "Worm Cocoon" ], [ "Underground Jungle" ], AnimalLocationFlag.main_path ),
    "lukki_eggs": AnimalLocation(113015, [ "Lukki Eggs", "Lukki Eggs" ], [ "Underground Jungle" ], AnimalLocationFlag.main_path ),
}

apotheosis_animal_mapping: Dict[str, AnimalLocation] = {
    "cat_mocreeps": AnimalLocation(112201, [ "Kissa", "Cat" ], [ "Forest" ], AnimalLocationFlag.main_path, ModFlag.apotheosis), # No kill catto, only pet!
    "bubble_liquid": AnimalLocation(112202, [ "Nestemäinen kupla", "Liquid Bubble" ], [ "Coal Pits", "The Vault", "Fungal Caverns" ], AnimalLocationFlag.main_path, ModFlag.apotheosis),
    "hiisi_thief": AnimalLocation(112203, [ "Varashiisi", "Thief Hiisi" ], [ "Mines", "Coal Pits", "Snowy Depths", "Fungal Caverns", "Ant Nest" ], AnimalLocationFlag.main_path, ModFlag.apotheosis),
    "hisii_minecart": AnimalLocation(112204, [ "Kaivoskärryhaulikkohiisi", "Minecart Hiisi" ], [ "Mines", "Coal Pits" ], AnimalLocationFlag.main_path, ModFlag.apotheosis),
    "hisii_minecart_tnt": AnimalLocation(112205, [ "Kaivoskärrytappurahaulikkohiisi", "Minecart Miner Hiisi" ], [ "Mines", "Coal Pits" ], AnimalLocationFlag.main_path, ModFlag.apotheosis),
    "hisii_giga_bomb": AnimalLocation(112206, [ "Psykopaattihiisi", "Giga Bomb Hiisi" ], [ "Mines" ], AnimalLocationFlag.never, ModFlag.apotheosis), #Part of a random set piece
    "hisii_engineer": AnimalLocation(112207, [ "Insinöörihiisi", "Hiisi Engineer" ], [ "Snowy Depths", "Hiisi Base", "Frozen Vault", "The Vault" ], AnimalLocationFlag.main_path, ModFlag.apotheosis),
    "hisii_rocketshotgun": AnimalLocation(112208, [ "Rakettihaulikkohiisi", "Rocket Shotgun Hiisi" ], [ "Underground Jungle", "The Vault", "Frozen Vault" ], AnimalLocationFlag.main_path, ModFlag.apotheosis),
    "hisii_hobo": AnimalLocation(112209, [ "Koditonhiisi", "Hiisi Hobo" ], [ "Forest", "Hisii Base", "The Vault", "Frozen Vault", "Lake" ], AnimalLocationFlag.main_path, ModFlag.apotheosis),
    "hisii_hobo_rich": AnimalLocation(112210, [ "Rikashiisi", "Rich Hiisi" ], [ "Unsorted" ], AnimalLocationFlag.never, ModFlag.apotheosis), #???
    "shaman_greater_apotheosis": AnimalLocation(112211, [ "Suur-Märkiäinen", "Greater Swampling" ], [ "Fungal Caverns", "Overgrown Cavern" ], AnimalLocationFlag.reasonable, ModFlag.apotheosis),
    "blindgazer": AnimalLocation(112212, [ "Sokeakatselija", "Blind Gazer" ], [ "The Vault", "Frozen Vault" ], AnimalLocationFlag.main_path, ModFlag.apotheosis),
    "slime_leaker_weak": AnimalLocation(112213, [ "Heikko Vuotavajaska", "Weak Leaking Slime" ], [ "Mines" ], AnimalLocationFlag.main_path, ModFlag.apotheosis),
    "slime_leaker": AnimalLocation(112214, [ "Vuotavajaska", "Leaking Slime" ], [ "Coal Pits", "The Vault" ], AnimalLocationFlag.main_path, ModFlag.apotheosis),
    "slime_teleporter": AnimalLocation(112215, [ "Säröilevä limanuljaska", "Warping Slime" ], [ "Unsorted" ], AnimalLocationFlag.never, ModFlag.apotheosis),
    "goo_slug": AnimalLocation(112216, [ "Liimanetana", "Glue Slug" ], [ "Mines", "Coal Pits", "The Vault" ], AnimalLocationFlag.main_path, ModFlag.apotheosis),
    "poring": AnimalLocation(112217, [ "Hyytelö", "Jelly" ], [ "Mines", "Coal Pits", "Desert", "Sandcave" ], AnimalLocationFlag.main_path, ModFlag.apotheosis),
    "poring_lukki": AnimalLocation(112218, [ "Lukkihyytelö", "Jelly Longlegs" ], [ "Unsorted" ], AnimalLocationFlag.never, ModFlag.apotheosis),
    "poring_magic": AnimalLocation(112219, [ "Lumottuhyytelö", "Magic Jelly" ], [ "Temple of the Art", "Wizards' Den", "Pyramid", "Magical Temple" ], AnimalLocationFlag.main_path, ModFlag.apotheosis),
    "poring_devil": AnimalLocation(112220, [ "Epäpyhähyytelö", "Unholy Jelly" ], [ "The Work (Hell)" ], AnimalLocationFlag.pain, ModFlag.apotheosis),
    "poring_holy": AnimalLocation(112221, [ "Jumalallinenhyytelö", "Divine Jelly" ], [ "The Work (Sky)" ], AnimalLocationFlag.pain, ModFlag.apotheosis),
    "poring_holy_arch": AnimalLocation(112222, [ "Korkeajumalallinenhyytelö", "High Divine Jelly" ], [ "The Work (Sky)" ], AnimalLocationFlag.pain, ModFlag.apotheosis), #Miniboss
    "blob_big": AnimalLocation(112223, [ "Isomöykky", "Big Blob" ], [ "The Vault", "Fungal Caverns", "Overgrown Cavern" ], AnimalLocationFlag.main_path, ModFlag.apotheosis),
    "blob_huge": AnimalLocation(112224, [ "Kammottavamöykky", "Creepy Blob" ], [ "Overgrown Cavern" ], AnimalLocationFlag.side_path, ModFlag.apotheosis),
    "ant_fire": AnimalLocation(112225, [ "Tulimurkku", "Fire Ant" ], [ "Ant Nest" ], AnimalLocationFlag.side_path, ModFlag.apotheosis),
    "ant_suffocate": AnimalLocation(112226, [ "Tukahduttajamurkku", "Suffocating Ant" ], [ "Ant Nest" ], AnimalLocationFlag.side_path, ModFlag.apotheosis),
    "ant_pheromone": AnimalLocation(112227, [ "Sairaanhoitajamurkku", "Nursing Ant" ], [ "Ant Nest" ], AnimalLocationFlag.side_path, ModFlag.apotheosis),
    "rat_birthday": AnimalLocation(112228, [ "Juhlarotta", "Birthday Rat" ], [ "Forest" ], AnimalLocationFlag.never, ModFlag.apotheosis), #Event
    "ccc_bat_psychic": AnimalLocation(112229, [ "Psyykkinenlepakko", "Psychic Bat" ], [ "Coal Pits" ], AnimalLocationFlag.main_path, ModFlag.apotheosis),
    "mudman_friendly": AnimalLocation(112230, [ "Mutamies", "Mudman" ], [ "Coal Pits" ], AnimalLocationFlag.reasonable, ModFlag.apotheosis),
    "ceiling_fungus": AnimalLocation(112231, [ "Kattosieni", "Ceiling Fungus" ], [ "Fungal Caverns", "Overgrown Cavern" ], AnimalLocationFlag.side_path, ModFlag.apotheosis),
    #fungus_tiny [ "Fungal Caverns", "Overgrown Cavern" ], AnimalLocationFlag.side_path, ModFlag.apotheosis)
    "poisonmushroom": AnimalLocation(112232, [ "Myrkyllinensieni", "Poisonous Mushroom" ], [ "Underground Jungle", "Lukki Lair", "Overgrown Cavern" ], AnimalLocationFlag.main_path, ModFlag.apotheosis),
    "fungus_smoking_creep": AnimalLocation(112233, [ "Savuavasieni", "Smoking Fungus" ], [ "Overgrown Cavern" ], AnimalLocationFlag.reasonable, ModFlag.apotheosis),
    "lukki_fungus": AnimalLocation(112234, [ "Revitty sieni", "Uprooted Fungus" ], [ "Fungal Caverns", "Overgrown Cavern" ], AnimalLocationFlag.side_path, ModFlag.apotheosis),
    "hideous_mass": AnimalLocation(112235, [ "Hirvittävämassa", "Hideous Mass" ], [ "Temple of the Art", "Pyramid" ], AnimalLocationFlag.main_path, ModFlag.apotheosis),
    "tentacler_big": AnimalLocation(112236, [ "Isoturso", "Big Tentacler" ], [ "The Vault", "Fungal Caverns", "Overgrown Cavern", "Temple of the Art" ], AnimalLocationFlag.main_path, ModFlag.apotheosis),
    "longleg_pillar": AnimalLocation(112237, [ "Kohoava Pilari-hämis", "Towering Pillar of Hamis" ], [ "Forest" ], AnimalLocationFlag.never, ModFlag.apotheosis),
    "lukki_swarmling": AnimalLocation(112238, [ "Nopealukki", "Swarmling Lukki" ], [ "Lukki Lair" ], AnimalLocationFlag.side_path, ModFlag.apotheosis),
    "sunken_creature": AnimalLocation(112239, [ "Sukelluskello", "Diving Bell" ], [ "Sunken Cavern" ], AnimalLocationFlag.pain, ModFlag.apotheosis),
    "lukki_fire_tiny": AnimalLocation(112240, [ "Pikku Tulihämähäkki", "Tiny Fire Spider" ], [ "Core Mines" ], AnimalLocationFlag.never, ModFlag.apotheosis),
    "lukki_fire_miniboss": AnimalLocation(112241, [ "Nuori Tulihämähäkki", "Juvenile Fire Spider" ], [ "Core Mines" ], AnimalLocationFlag.pain, ModFlag.apotheosis),
    "giant_centipede": AnimalLocation(112242, [ "Nuori Tuhatjalkainen", "Juvenile Centipede" ], [ "Underground Jungle" ], AnimalLocationFlag.main_path, ModFlag.apotheosis),
    "locust_swarm": AnimalLocation(112243, [ "Heinäsirkka", "Locust Swarm" ], [ "Underground Jungle", "Pyramid", "Desert" ], AnimalLocationFlag.main_path, ModFlag.apotheosis),
    "devourer_magic": AnimalLocation(112244, [ "Taikainen syöjä", "Magic Devourer" ], [ "Underground Jungle", "Sandcave", "Snowy Chasm", "Temple of the Art", "Pyramid", "Ancient Laboratory" ], AnimalLocationFlag.main_path, ModFlag.apotheosis),
    "seeker": AnimalLocation(112245, [ "Etsijä", "Seeker" ], [ "Power Plant" ], AnimalLocationFlag.pain, ModFlag.apotheosis),
    "miniboss_pit_02": AnimalLocation(112246, [ "Wandsin Arvostelija", "Appreciator of Wands" ], [ "Sunken Cavern", "Temple of Sacrilegious Remains" ], AnimalLocationFlag.pain, ModFlag.apotheosis),
    "star_child": AnimalLocation(112247, [ "Tähtilapsi", "Star Child" ], [ "Temple of the Art", "The Work (Sky)" ], AnimalLocationFlag.main_path, ModFlag.apotheosis),
    "worm_wall": AnimalLocation(112248, [ "Seinätoukka", "Wall Worm" ], [ "The Laboratory" ], AnimalLocationFlag.pain, ModFlag.apotheosis), #Technically spawns everywhere inside deep rock.
    "worm_maggot_big": AnimalLocation(112249, [ "Pieni Limatoukka", "Small Slimy Maggot" ], [ "Meat Realm" ], AnimalLocationFlag.never, ModFlag.apotheosis),
    "worm_end_big_apotheosis": AnimalLocation(112250, [ "Suur-Helvetinmato", "Greater Hell Worm" ], [ "The Work (Hell)" ], AnimalLocationFlag.pain, ModFlag.apotheosis),
    "worm_mechanical": AnimalLocation(112251, [ "Mekaaninenmato", "Mechanical Worm" ], [ "The Vault" ], AnimalLocationFlag.reasonable, ModFlag.apotheosis),
    "worm_spine": AnimalLocation(112252, [ "Kirottuselkäranka", "Cursed Spine" ], [ "Temple of Sacrilegious Remains"  ], AnimalLocationFlag.pain, ModFlag.apotheosis),
    "drone_status_ailment": AnimalLocation(112253, [ "Parannuskeinolennokki", "Ailment Drone" ], [ "The Vault", "Fungal Caverns", "Frozen Vault" ], AnimalLocationFlag.main_path, ModFlag.apotheosis),
    "drone_mini": AnimalLocation(112254, [ "Pieni Lennokki", "Mini Drone" ], [ "Hiisi Base", "The Vault", "Frozen Vault", "Power Plant" ], AnimalLocationFlag.main_path, ModFlag.apotheosis),
    "gazer_robot": AnimalLocation(112255, [ "Aluebotti", "Zoner" ], [ "Power Plant" ], AnimalLocationFlag.pain, ModFlag.apotheosis),
    "tesla_turret": AnimalLocation(112256, [ "Teslatötterö", "Tesla Turret" ], [ "Hiisi Base", "Snowy Depths", "Desert", "Power Plant" ], AnimalLocationFlag.main_path, ModFlag.apotheosis),
    "c_basebot_speeder_apotheosis": AnimalLocation(112257, [ "Johtaja", "Manager" ], [ "Power Plant" ], AnimalLocationFlag.pain, ModFlag.apotheosis),
    "tank_flame_apotheosis": AnimalLocation(112258, [ "Sytytystankki", "Ignition Tank" ], [ "Hiisi Base", "The Vault", "Frozen Vault" ], AnimalLocationFlag.main_path, ModFlag.apotheosis),
    "waterskull": AnimalLocation(112259, [ "Vesiö", "Water Spirit" ], [ "Ant Nest", "Forest" ], AnimalLocationFlag.side_path, ModFlag.apotheosis),
    "wizard_firemage_greater": AnimalLocation(112260, [ "Suur-Stendari", "Greater Fire Mage" ], [ "Wizards' Den", "The Works (Hell)" ], AnimalLocationFlag.side_path, ModFlag.apotheosis),
    "watermage": AnimalLocation(112261, [ "Vesimagi", "Water Mage" ], [ "Mines", "Temple of the Art", "Sunken Cavern" ], AnimalLocationFlag.main_path, ModFlag.apotheosis),
    "watermage_greater": AnimalLocation(112262, [ "Suur-Vesimagi", "Greater Water Mage" ], [ "Sunken Cavern" ], AnimalLocationFlag.pain, ModFlag.apotheosis),
    "barfer_greater_apotheosis": AnimalLocation(112263, [ "Suur-Turvonnu velho", "Greater Barfer" ], [ "Unsorted" ], AnimalLocationFlag.never, ModFlag.apotheosis),
    "wizard_ambrosia": AnimalLocation(112264, [ "Kuolemattomuudenmestari", "Master of Immortality" ], [ "Wizards' Den" ], AnimalLocationFlag.side_path, ModFlag.apotheosis),
    "wizard_copeseethmald": AnimalLocation(112265, [ "Uistelunmestari", "Master of Trolling" ], [ "Desert Chasm", "Fungal Caverns" ], AnimalLocationFlag.reasonable, ModFlag.apotheosis),
    "wizard_duck": AnimalLocation(112266, [ "Sinisorsienmestari", "Master of Mallards" ], [ "Temple of the Art", "Wizards' Den", "Ancient Laboratory" ], AnimalLocationFlag.main_path, ModFlag.apotheosis),
    "enchanted_duck": AnimalLocation(112267, [ "Lumottu ankka", "Enchanted Duck" ], [ "Temple of the Art", "Wizards' Den", "Ancient Laboratory" ], AnimalLocationFlag.never, ModFlag.apotheosis), # Spawn of Wizard Duck
    "wizard_explosive": AnimalLocation(112268, [ "Räjähteidenmestari", "Master of Explosives" ], [ "Wizards' Den" ], AnimalLocationFlag.side_path, ModFlag.apotheosis),
    "wizard_jackofalltrades": AnimalLocation(112269, [ "Eimitäänmestari", "Master of None" ], [ "The Vault", "Wizards' Den", "Underground Jungle", "Lukki lair" ], AnimalLocationFlag.main_path, ModFlag.apotheosis),
    "wizard_manaeater": AnimalLocation(112270, [ "Mananmestari", "Master of Mana" ], [ "Temple of the Art", "Wizards' Den", "Pyramid", "Ancient Laboratory", "Magical Temple" ], AnimalLocationFlag.main_path, ModFlag.apotheosis),
    "wizard_transmutation": AnimalLocation(112271, [ "Transmutaatioidenmestari", "Master of Transmutation" ], [ "The Vault", "Wizards' Den", "Lukki lair", "Overgrown Cavern",  ], AnimalLocationFlag.main_path, ModFlag.apotheosis),
    "wizard_z_poly_miniboss": AnimalLocation(112272, [ "Yli-innokas Muudonmuutosmestari", "Overzealous Master of Polymorphing" ], [ "Wizards' Den", "Temple of the Art" ], AnimalLocationFlag.pain, ModFlag.apotheosis), #Miniboss
    "wizard_corrupt_wands": AnimalLocation(112273, [ "Nukketeatterinmestari", "Master of Puppets" ], [ "Temple of Sacrilegious Remains" ], AnimalLocationFlag.pain, ModFlag.apotheosis),
    "wizard_corrupt_ambrosia": AnimalLocation(112274, [ "Korruptoitunut Kuolemattomuudenmestari", "Corrupt Master of Immortality" ], [ "Temple of Sacrilegious Remains" ], AnimalLocationFlag.pain, ModFlag.apotheosis),
    "wizard_corrupt_returner": AnimalLocation(112275, [ "Korruptoitunut Palauttajamestari", "Corrupt Master of Returning" ], [ "Temple of Sacrilegious Remains" ], AnimalLocationFlag.pain, ModFlag.apotheosis),
    "wizard_corrupt_hearty": AnimalLocation(112276, [ "Korruptoitunut Haavoittajamestari", "Corrupt Master of Wounding" ], [ "Temple of Sacrilegious Remains" ], AnimalLocationFlag.pain, ModFlag.apotheosis),
    "wizard_corrupt_manaeater": AnimalLocation(112277, [ "Korruptoitunut Mananmestari", "Corrupt Master of Mana" ], [ "Temple of Sacrilegious Remains" ], AnimalLocationFlag.pain, ModFlag.apotheosis),
    "wizard_corrupt_neutral": AnimalLocation(112278, [ "Korruptoitunut Maadoittajamestari", "Corrupt Master of Grounding" ], [ "Temple of Sacrilegious Remains" ], AnimalLocationFlag.pain, ModFlag.apotheosis),
    "wizard_corrupt_swapper": AnimalLocation(112279, [ "Korruptoitunut Vaihdosmestari", "Corrupt Master of Exchange" ], [ "Temple of Sacrilegious Remains" ], AnimalLocationFlag.pain, ModFlag.apotheosis),
    "wizard_corrupt_teleport": AnimalLocation(112280, [ "Korruptoitunut Siirtäjämestari", "Corrupt Master of Teleportation" ], [ "Temple of Sacrilegious Remains" ], AnimalLocationFlag.pain, ModFlag.apotheosis),
    "wizard_corrupt_twitchy": AnimalLocation(112281, [ "Korruptoitunut Sätkymestari", "Corrupt Master of Twitching" ], [ "Temple of Sacrilegious Remains" ], AnimalLocationFlag.pain, ModFlag.apotheosis),
    "wizard_corrupt_weaken": AnimalLocation(112282, [ "Korruptoitunut Turvattomuusmestari", "Corrupt Master of Vulnerability" ], [ "Temple of Sacrilegious Remains" ], AnimalLocationFlag.pain, ModFlag.apotheosis),
    "lukki_tentacle_hungry": AnimalLocation(112283, [ "Kirottuolento", "Cursed Being" ], [ "Temple of Sacrilegious Remains" ], AnimalLocationFlag.pain, ModFlag.apotheosis),
    "flesh_wizard_wands": AnimalLocation(112284, [ "Kirottu Nukketaiteilija", "Cursed Puppeteer" ], [ "Temple of Sacrilegious Remains" ], AnimalLocationFlag.pain, ModFlag.apotheosis),
    "flesh_wizard_manaeater": AnimalLocation(112285, [ "Kirottu Manavampyyri", "Cursed Manasapper" ], [ "Temple of Sacrilegious Remains" ], AnimalLocationFlag.pain, ModFlag.apotheosis),
    "flesh_wizard_neutral": AnimalLocation(112286, [ "Kirottu Neutraloija", "Cursed Grounder" ], [ "Temple of Sacrilegious Remains" ], AnimalLocationFlag.pain, ModFlag.apotheosis),
    "flesh_wizard_swapper": AnimalLocation(112287, [ "Kirottu Korvaaja", "Cursed Swapper" ], [ "Temple of Sacrilegious Remains" ], AnimalLocationFlag.pain, ModFlag.apotheosis),
    "flesh_wizard_twitchy": AnimalLocation(112288, [ "Kirottu Sätkijä", "Cursed Twitcher" ], [ "Temple of Sacrilegious Remains" ], AnimalLocationFlag.pain, ModFlag.apotheosis),
    "wraith_weirdo_shield": AnimalLocation(112289, [ "Härö", "Weirdo" ], [ "Temple of the Art", "The Vault", "Sandcave" ], AnimalLocationFlag.main_path, ModFlag.apotheosis),
    "wraith_returner_apotheosis": AnimalLocation(112290, [ "Heijastava Härö", "Reflective Weirdo" ], [ "Temple of the Art", "Pyramid", "The Work (Sky)" ], AnimalLocationFlag.main_path, ModFlag.apotheosis),
    "wraith_alchemy_apotheosis": AnimalLocation(112291, [ "Alkeeminen Härö", "Alchemic Weirdo" ], [ "Temple of Sacrilegious Remains" ], AnimalLocationFlag.pain, ModFlag.apotheosis),
    "whisp": AnimalLocation(112292, [ "Virvatuli", "Will o' the whisp" ], [ "Coal Pits", "Core Mines", "Sandcave" ], AnimalLocationFlag.main_path, ModFlag.apotheosis),
    "whisp_big": AnimalLocation(112293, [ "Jättivirvatuli", "Giant Will o' the whisp" ], [ "Core Mines", "The Tower" ], AnimalLocationFlag.reasonable, ModFlag.apotheosis),
    "whisp_giga": AnimalLocation(112294, [ "Kolossaalinenvirvatuli", "Colossal Will o' the whisp" ], [ "Unsorted" ], AnimalLocationFlag.never, ModFlag.apotheosis), #Secret?
    "fairy_cheap": AnimalLocation(112295, [ "Keiju", "Fairy" ], [ "Mines", "Coal Pits", "Underground Jungle" ], AnimalLocationFlag.main_path, ModFlag.apotheosis),
    "fairy_big": AnimalLocation(112296, [ "Jättikeiju", "Giant Fairy" ], [ "Coal Pits", "Underground Jungle" ], AnimalLocationFlag.main_path, ModFlag.apotheosis),
    "fairy_giant": AnimalLocation(112297, [ "Kolossaalinenkeiju", "Colossal Fairy" ], [ "Unsorted" ], AnimalLocationFlag.never, ModFlag.apotheosis), #Secret?
    "fairy_big_discord": AnimalLocation(112298, [ "Jättiristiriitakeiju", "Giant Discord Fairy" ], [ "Temple of the Art", "The Work (Sky)", "Sandcave" ], AnimalLocationFlag.main_path, ModFlag.apotheosis),
    "fairy_esoteric": AnimalLocation(112299, [ "Esoteerinenpäiväuni", "Esoteric Fairy" ], [ "Temple of the Art" ], AnimalLocationFlag.reasonable, ModFlag.apotheosis),
    "esoteric_being": AnimalLocation(112300, [ "Esoteerinenolento", "Esoteric Being" ], [ "Temple of the Art", "Magical Temple" ], AnimalLocationFlag.reasonable, ModFlag.apotheosis),
    "worm_esoteric": AnimalLocation(112301, [ "Esoteerinenmato", "Esoteric Worm" ], [ "Unsorted" ], AnimalLocationFlag.never, ModFlag.apotheosis),
    "musical_being": AnimalLocation(112302, [ "Kuulumaton", "Unheard" ], [ "Pyramid", "Snowy Chasm", "Sandcave" ], AnimalLocationFlag.reasonable, ModFlag.apotheosis),
    "musical_being_weak": AnimalLocation(112303, [ "Hiljainen", "Quiet" ], [ "Snowy Chasm" ], AnimalLocationFlag.reasonable, ModFlag.apotheosis),
    "phantom_c_apotheosis": AnimalLocation(112304, [ "Pakkomielteinenkalma", "Obsessive Phantom" ], [ "Unsorted" ], AnimalLocationFlag.never, ModFlag.apotheosis),
    "devourer_ghost": AnimalLocation(112305, [ "Nälkäinenaave", "Devouring Phantom" ], [ "Temple of the Art", "Magical Temple", "Pyramid" ], AnimalLocationFlag.main_path, ModFlag.apotheosis),
    "ghost_bow": AnimalLocation(112306, [ "Haamujousi", "Phantom Bow" ], [ "Magical Temple" ], AnimalLocationFlag.side_path, ModFlag.apotheosis),
    "forsaken_eye": AnimalLocation(112307, [ "Hylättysilmä", "Forsaken Eye" ], [ "Snowy Depths", "Snowy Chasm", "Wizards' Den" ], AnimalLocationFlag.main_path, ModFlag.apotheosis),
    "spirit_healing": AnimalLocation(112308, [ "Parantava-Aave", "Healing Spirit" ], [ "Pyramid", "Coal Pits" ], AnimalLocationFlag.reasonable, ModFlag.apotheosis),
    "gazer_greater": AnimalLocation(112309, [ "Suur-Helvetinkatse", "Greater Hell Gazer" ], [ "The Work (Hell)" ], AnimalLocationFlag.pain, ModFlag.apotheosis),
    "gazer_greater_sky": AnimalLocation(112310, [ "Suur-Taivaankatse", "Greater Sky Gazer" ], [ "The Work (Sky)" ], AnimalLocationFlag.pain, ModFlag.apotheosis),
    "gazer_cold_apotheosis": AnimalLocation(112311, [ "Jäänkatse", "Cold Gazer" ], [ "Snowy Depths", "Snowy Chasm" ], AnimalLocationFlag.side_path, ModFlag.apotheosis),
    "gazer_greater_cold": AnimalLocation(112312, [ "Suur-Jäänkatse", "Greater Cold Gazer" ], [ "Snowy Depths", "Snowy Chasm" ], AnimalLocationFlag.reasonable, ModFlag.apotheosis),
    "gazer_parasitic": AnimalLocation(112313, [ "Parasiittinenkatse", "Parasitic Gazer" ], [ "Virulent Caverns" ], AnimalLocationFlag.never, ModFlag.apotheosis),
    "sentry": AnimalLocation(112314, [ "Vartiomies", "Sentry" ], [ "The Vault", "The Work (Hell)", "Frozen Vault", "Snowy Depths" ], AnimalLocationFlag.main_path, ModFlag.apotheosis),
    "triangle_gem": AnimalLocation(112315, [ "Kolmionmuotoinenkristalli", "Triangular Gem" ], [ "Temple of the Art", "Sandcave" ], AnimalLocationFlag.main_path, ModFlag.apotheosis),
    "mimic_explosive_box": AnimalLocation(112316, [ "Räjähdysherkkämatkija", "Explosive Box Mimic" ], [ "Mines", "Coal Pits", "The Vault", "Hiisi Base" ], AnimalLocationFlag.main_path, ModFlag.apotheosis),
    "snowman": AnimalLocation(112317, [ "Lumiukko", "Snowman" ], [ "Snowy Depths" ], AnimalLocationFlag.never, ModFlag.apotheosis), #Event enemy
    "mimic_perk_twwe": AnimalLocation(112318, [ "Paskiainen", "Tinker With Wands Everywhere Mimic" ], [ "Coal Pits" ], AnimalLocationFlag.never, ModFlag.apotheosis),
    "hiisi_chef_hell": AnimalLocation(112319, [ "Hornakokkihiisi", "Hell Chef" ], [ "The Work (Hell)" ], AnimalLocationFlag.never, ModFlag.apotheosis),
    "boss_toxic_worm_parallel": AnimalLocation(112320, [ "Madon Muisti", "Worm Memory" ], [ "Coal Pits" ], AnimalLocationFlag.reasonable, ModFlag.apotheosis),
    "boss_toxic_worm": AnimalLocation(112321, [ "Jättimäinenmyrkkymato", "Giant Toxic Worm" ], [ "Coal Pits" ], AnimalLocationFlag.never, ModFlag.apotheosis),
    "boss_toxic_worm_minion": AnimalLocation(112322, [ "Myrkyllinenmato", "Toxic Worm" ], [ "Coal Pits" ], AnimalLocationFlag.never, ModFlag.apotheosis), #Spawned by boss man
    "boss_musical_ghost": AnimalLocation(112323, [ "Hylättyorkesteri", "Abandoned Orchestra" ], [ "Sandcave" ], AnimalLocationFlag.never, ModFlag.apotheosis),
    "blob_titan": AnimalLocation(112324, [ "Kolossaalimöykky", "Colossal Blob" ], [ "Overgrown Cavern" ], AnimalLocationFlag.never, ModFlag.apotheosis),
    "boss_fire_lukki": AnimalLocation(112325, [ "Tulen Esteetikko", "Aesthete of Heat" ], [ "Lava Lake" ], AnimalLocationFlag.never, ModFlag.apotheosis),
    "boss_flesh_monster": AnimalLocation(112326, [ "Kerettiläinenhirviö", "Heretical Monster" ], [ "Temple of Sacrilegious Remains" ], AnimalLocationFlag.never, ModFlag.apotheosis),
    "forest_monolith": AnimalLocation(112327, [ "Monoliitti", "Monolith" ], [ "Forest" ], AnimalLocationFlag.never, ModFlag.apotheosis),
}