from enum import IntEnum
from typing import Dict, NamedTuple

class AnimalLocationFlag(IntEnum):
    none = 0
    main_path = 1
    side_path = 2
    reasonable = 3
    pain = 4
    never = 99

class AnimalLocation(NamedTuple):
    id: int
    names: list
    regions: list
    flag: AnimalLocationFlag = 99
    ltype = "Kill"

location_animal_mapping: Dict[str, AnimalLocation] = {
    "player": AnimalLocation(112001, [ "Minä", "Me" ], [ "Forest" ], AnimalLocationFlag.main_path),
    "sheep": AnimalLocation(112002, [ "Lammas", "Sheep" ], [ "Lake" ], AnimalLocationFlag.reasonable),
    "sheep_bat": AnimalLocation(112003, [ "Lentolammas", "Flying Sheep" ], [ "Forest" ], AnimalLocationFlag.reasonable),
    "sheep_fly": AnimalLocation(112004, [ "Suhiseva lammas", "Buzzing Sheep" ], [ "Forest" ], AnimalLocationFlag.reasonable),
    "scorpion": AnimalLocation(112005, [ "Skorpioni", "Scorpion" ], [ "Pyramid", "Temple of the Art", "Watchtower", "Wizards' Den" ], AnimalLocationFlag.main_path),
    "fish": AnimalLocation(112006, [ "Eväkäs", "Fish" ], [ "Forest", "Snowy Depths Holy Mountain", "Lake", "Hiisi Base" ], AnimalLocationFlag.main_path),
    "fish_large": AnimalLocation(112007, [ "Suureväkäs", "Large Fish" ], [ "Lake", "Snowy Depths" ], AnimalLocationFlag.side_path),
    "duck": AnimalLocation(112008, [ "Ankka", "Duck" ], [ "Lake" ], AnimalLocationFlag.reasonable),
    "wolf": AnimalLocation(112009, [ "Susi", "Wolf" ], [ "Lake", "The Tower" ], AnimalLocationFlag.reasonable),
    "deer": AnimalLocation(112010, [ "Nelikoipi", "Deer" ], [ "Lake" ], AnimalLocationFlag.reasonable),
    "elk": AnimalLocation(112011, [ "Poro", "Reindeer" ], [ "Lake" ], AnimalLocationFlag.reasonable),
    "eel": AnimalLocation(112012, [ "Nahkiainen", "Lamprey" ], [ "Lake" ], AnimalLocationFlag.reasonable),
    "zombie_weak": AnimalLocation(112013, [ "Heikkohurtta", "Weak Hound" ], [ "Mines" ], AnimalLocationFlag.main_path),
    "zombie": AnimalLocation(112014, [ "Hurtta", "Hound" ], [ "Collapsed Mines", "Fungal Caverns", "The Tower" ], AnimalLocationFlag.main_path),
    "miner_weak": AnimalLocation(112015, [ "Tappurahiisiläinen", "Weak Hiisi Miner" ], [ "Mines", "Coal Pits" ], AnimalLocationFlag.main_path),
    "miner": AnimalLocation(112016, [ "Tappurahiisi", "Miner Hiisi" ], [ "Collapsed Mines", "Coal Pits", "The Tower" ], AnimalLocationFlag.main_path),
    "miner_fire": AnimalLocation(112017, [ "Tulihiisi", "Fire Hiisi" ], [ "Collapsed Mines", "Coal Pits", "The Tower" ], AnimalLocationFlag.main_path),
    "miner_santa": AnimalLocation(112018, [ "Jouluhiisi", "Christmas Hiisi" ], [ "Mines", "Collapsed Mines", "Coal Pits" ], AnimalLocationFlag.never),
    "miner_chef": AnimalLocation(112019, [ "Kokkihiisi", "Hiisi Chef" ], [ "Hiisi Base" ], AnimalLocationFlag.never),
    "goblin_bomb": AnimalLocation(112020, [ "Sähikäismenninkäinen", "Firecracker Goblin" ], [ "Coal Pits", "The Tower" ], AnimalLocationFlag.main_path),
    "shotgunner_weak": AnimalLocation(112021, [ "Heikko haulikkohiisi", "Weak Shotgun Hiisi" ], [ "Mines" ], AnimalLocationFlag.main_path),
    "shotgunner": AnimalLocation(112022, [ "Haulikkohiisi", "Shotgun Hiisi" ], [ "Mines", "Collapsed Mines", "Coal Pits", "Snowy Depths", "Hiisi Base", "The Tower" ], AnimalLocationFlag.main_path),
    "scavenger_smg": AnimalLocation(112023, [ "Rynkkyhiisi", "Hiisi Gunner" ], [ "Snowy Depths", "Hiisi Base", "Underground Jungle", "The Vault", "Sandcave", "Desert Chasm", "Frozen Vault", "Snowy Chasm", "The Tower" ], AnimalLocationFlag.main_path),
    "scavenger_grenade": AnimalLocation(112024, [ "Kranuhiisi", "Hiisi Grenadier" ], [ "Snowy Depths", "Hiisi Base", "Underground Jungle", "The Vault", "Sandcave", "Desert Chasm", "Frozen Vault", "Snowy Chasm", "The Tower" ], AnimalLocationFlag.main_path),
    "scavenger_mine": AnimalLocation(112025, [ "Miinankylväjä", "Hiisi Mine Thrower" ], [ "Coal Pits", "Snowy Depths", "Hiisi Base", "Underground Jungle", "The Vault", "Sandcave", "Frozen Vault", "The Tower" ], AnimalLocationFlag.main_path),
    "scavenger_heal": AnimalLocation(112026, [ "Parantajahiisi", "Hiisi Healer" ], [ "Hiisi Base", "Underground Jungle", "The Vault", "Sandcave", "Frozen Vault", "The Tower" ], AnimalLocationFlag.main_path),
    "scavenger_glue": AnimalLocation(112027, [ "Liimahiisi", "Glue Hiisi" ], [ "Snowy Depths", "The Vault", "Frozen Vault", "Power Plant" ], AnimalLocationFlag.main_path),
    "scavenger_invis": AnimalLocation(112028, [ "Häivehiisi", "Stealth Hiisi" ], [ "Fungal Caverns", "Frozen Vault", "Sandcave" ], AnimalLocationFlag.main_path),
    "scavenger_shield": AnimalLocation(112029, [ "Kilpihiisi", "Shield Hiisi" ], [ "Fungal Caverns", "Frozen Vault", "The Tower" ], AnimalLocationFlag.side_path),
    "scavenger_poison": AnimalLocation(112030, [ "Myrkkyhiisi", "Hiisi Poisoner" ], [ "Underground Jungle", "Sandcave", "The Tower" ], AnimalLocationFlag.main_path),
    "scavenger_clusterbomb": AnimalLocation(112031, [ "Isohiisi", "Hiisi Bomber" ], [ "Hiisi Base", "Underground Jungle", "Sandcave", "The Tower" ], AnimalLocationFlag.main_path),
    "scavenger_leader": AnimalLocation(112032, [ "Toimari", "Hiisi Leader" ], [ "Snowy Depths", "Hiisi Base", "Underground Jungle", "The Vault", "Frozen Vault", "Sandcave", "Desert Chasm", "The Tower" ], AnimalLocationFlag.main_path),
    "alchemist": AnimalLocation(112033, [ "Puistokemisti", "Hiisi Alchemist" ], [ "Mines", "Coal Pits", "Fungal Caverns", "Pyramid", "Overgrown Cavern", "The Tower" ], AnimalLocationFlag.main_path),
    "sniper": AnimalLocation(112034, [ "Snipuhiisi", "Hiisi Sniper" ], [ "Snowy Depths", "Hiisi Base", "The Vault", "The Tower" ], AnimalLocationFlag.main_path),
    "shaman": AnimalLocation(112035, [ "Märkiäinen", "Swampling" ], [ "Mines", "Collapsed Mines", "Underground Jungle" ], AnimalLocationFlag.main_path),
    "coward": AnimalLocation(112036, [ "Raukka", "Coward" ], [ "Hiisi Base", "Underground Jungle", "The Vault", "Frozen Vault", "The Tower" ], AnimalLocationFlag.main_path),
    "flamer": AnimalLocation(112037, [ "Liekkari", "Flamer" ], [ "Underground Jungle", "The Vault", "The Tower" ], AnimalLocationFlag.main_path),
    "icer": AnimalLocation(112038, [ "Jäähdytyslaite", "Icer" ], [ "The Vault", "Frozen Vault", "The Tower" ], AnimalLocationFlag.main_path),
    "bigzombie": AnimalLocation(112039, [ "Mätänevä ruumis", "Rotting Corpse" ], [ "The Vault", "Frozen Vault", "Fungal Caverns", "The Tower" ], AnimalLocationFlag.main_path),
    "bigzombietorso": AnimalLocation(112040, [ "Mätänevä kroppa", "Rotting Body" ], [ "The Vault", "Frozen Vault", "Fungal Caverns", "The Tower" ], AnimalLocationFlag.main_path),
    "bigzombiehead": AnimalLocation(112041, [ "Mätänevä pää", "Rotting Head" ], [ "The Vault", "Frozen Vault", "Fungal Caverns", "The Tower" ], AnimalLocationFlag.main_path),
    "slimeshooter_weak": AnimalLocation(112042, [ "Heikko limanuljaska", "Weak Toxic Slime" ], [ "Mines" ], AnimalLocationFlag.main_path),
    "slimeshooter": AnimalLocation(112043, [ "Limanuljaska", "Toxic Slime" ], [ "Coal Pits", "Fungal Caverns", "Snowy Depths", "The Tower" ], AnimalLocationFlag.main_path),
    "acidshooter_weak": AnimalLocation(112044, [ "Heikko happonuljaska", "Weak Acid Slime" ], [ "Mines" ], AnimalLocationFlag.main_path),
    "acidshooter": AnimalLocation(112045, [ "Happonuljaska", "Acid Slime" ], [ "Mines", "Fungal Caverns", "The Vault", "Temple of the Art", "Frozen Vault", "The Tower" ], AnimalLocationFlag.main_path),
    "lasershooter": AnimalLocation(112046, [ "Mulkkio", "Gazer" ], [ "The Vault", "Frozen Vault", "Temple of the Art", "The Tower" ], AnimalLocationFlag.main_path),
    "giantshooter_weak": AnimalLocation(112047, [ "Heikko äitinuljaska", "Weak Mother Slime" ], [ "Mines" ], AnimalLocationFlag.main_path),
    "giantshooter": AnimalLocation(112048, [ "Äitinuljaska", "Mother Slime" ], [ "Mines", "Fungal Caverns", "The Tower" ], AnimalLocationFlag.main_path),
    "miniblob": AnimalLocation(112049, [ "Möykky", "Blob" ], [ "Fungal Caverns", "Overgrown Cavern", "The Vault", "Frozen Vault", "The Tower" ], AnimalLocationFlag.main_path),
    "blob": AnimalLocation(112050, [ "Kiukkumöykky", "Angry Blob" ], [ "Fungal Caverns", "Overgrown Cavern", "The Vault", "Frozen Vault", "The Tower" ], AnimalLocationFlag.main_path),
    "ant": AnimalLocation(112051, [ "Murkku", "Ant" ], [ "Fungal Caverns", "Overgrown Cavern", "The Tower" ], AnimalLocationFlag.side_path),
    "rat": AnimalLocation(112052, [ "Rotta", "Rat" ], [ "Mines", "Coal Pits", "Fungal Caverns", "Snowy Depths", "Hiisi Base", "Meat Realm", "The Tower" ], AnimalLocationFlag.main_path),
    "bat": AnimalLocation(112053, [ "Lepakko", "Bat" ], [ "Coal Pits", "The Tower" ], AnimalLocationFlag.main_path),
    "bigbat": AnimalLocation(112054, [ "Suurlepakko", "Large Bat" ], [ "Coal Pits", "The Tower" ], AnimalLocationFlag.main_path),
    "firebug": AnimalLocation(112055, [ "Pikkutulikärpänen", "Lesser firefly" ], [ "Coal Pits", "The Tower" ], AnimalLocationFlag.main_path),
    "bigfirebug": AnimalLocation(112056, [ "Suurtulikärpänen", "Greater firefly" ], [ "Coal Pits", "The Tower" ], AnimalLocationFlag.main_path),
    "bloom": AnimalLocation(112057, [ "Puska", "Bloom" ], [ "Underground Jungle", "The Tower" ], AnimalLocationFlag.main_path),
    "shooterflower": AnimalLocation(112058, [ "Plasmakukka", "Plasma Flower" ], [ "Underground Jungle", "The Tower" ], AnimalLocationFlag.main_path),
    "fly": AnimalLocation(112059, [ "Amppari", "Wasp" ], [ "Underground Jungle", "Fungal Caverns", "The Tower" ], AnimalLocationFlag.main_path),
    "frog": AnimalLocation(112060, [ "Konna", "Toad" ], [ "Collapsed Mines", "Fungal Caverns", "The Tower" ], AnimalLocationFlag.side_path),
    "frog_big": AnimalLocation(112061, [ "Jättikonna", "Big Toad" ], [ "Collapsed Mines", "Fungal Caverns", "Overgrown Cavern", "The Tower" ], AnimalLocationFlag.side_path),
    "fungus": AnimalLocation(112062, [ "Laahustussieni", "Shuffling Fungus" ], [ "Mines", "Fungal Caverns", "Overgrown Cavern", "Underground Jungle", "The Tower", "Lukki Lair" ], AnimalLocationFlag.main_path),
    "fungus_big": AnimalLocation(112063, [ "Nuijamalikka", "Club-foot" ], [ "Fungal Caverns", "Overgrown Cavern", "Mines", "The Tower", "Lukki Lair" ], AnimalLocationFlag.side_path),
    "fungus_giga": AnimalLocation(112064, [ "Huhtasieni", "Pollen Morel" ], [ "Overgrown Cavern", "The Tower" ], AnimalLocationFlag.side_path),
    "lurker": AnimalLocation(112065, [ "Varjokupla", "Shadow Bubble" ], [ "Lukki Lair" ], AnimalLocationFlag.reasonable),
    "maggot": AnimalLocation(112066, [ "Toukka", "Maggot" ], [ "Underground Jungle", "Fungal Caverns", "The Vault", "Temple of the Art", "The Tower" ], AnimalLocationFlag.main_path),
    "skullrat": AnimalLocation(112067, [ "Kallorotta", "Skull Rat" ], [ "Pyramid", "Temple of the Art", "The Tower" ], AnimalLocationFlag.main_path),
    "skullfly": AnimalLocation(112068, [ "Kallokärpänen", "Skull Fly" ], [ "Pyramid", "Temple of the Art", "The Tower" ], AnimalLocationFlag.main_path),
    "tentacler_small": AnimalLocation(112069, [ "Pikkuturso", "Small Tentacler" ], [ "Fungal Caverns", "Temple of the Art", "The Tower" ], AnimalLocationFlag.main_path),
    "tentacler": AnimalLocation(112070, [ "Turso", "Tentacler" ], [ "Fungal Caverns", "The Vault", "Temple of the Art", "The Tower" ], AnimalLocationFlag.main_path),
    "ghoul": AnimalLocation(112071, [ "Sylkyri", "Spitter" ], [ "The Tower" ], AnimalLocationFlag.pain),
    "giant": AnimalLocation(112072, [ "Hiidenkivi", "Rock Giant" ], [ "Snowy Depths", "The Tower" ], AnimalLocationFlag.main_path),
    "pebble": AnimalLocation(112073, [ "Lohkare", "Rock Spirit" ], [ "Snowy Depths", "The Tower" ] ),
    "longleg": AnimalLocation(112074, [ "Hämis", "Spidey" ], [ "Mines", "Collapsed Mines", "Pyramid", "Temple of the Art", "The Tower" ], AnimalLocationFlag.main_path),
    "lukki_tiny": AnimalLocation(112075, [ "Pikkuhämähäkki", "Small Spider" ], [ "Underground Jungle" ], AnimalLocationFlag.main_path),
    "lukki": AnimalLocation(112076, [ "Hämähäkki", "Spider" ], [ "Underground Jungle", "Lukki Lair" ], AnimalLocationFlag.main_path),
    "lukki_longleg": AnimalLocation(112077, [ "Lukki", "Daddy Longlegs" ], [ "Underground Jungle" ], AnimalLocationFlag.main_path),
    "lukki_creepy_long": AnimalLocation(112078, [ "Kasvoton Lukki", "Faceless spider" ], [ "Lukki Lair" ], AnimalLocationFlag.reasonable),
    "lukki_dark": AnimalLocation(112079, [ "Kammolukki", "Toothy spider" ], [ "Lukki Lair" ], AnimalLocationFlag.reasonable),
    "worm_tiny": AnimalLocation(112080, [ "Pikkumato", "Small Worm" ], [ "Snowy Depths" ], AnimalLocationFlag.reasonable),
    "worm": AnimalLocation(112081, [ "Mato", "Worm" ], [ "Mines", "Collapsed Mines", "Snowy Depths", "Underground Jungle", "Temple of the Art", "Meat Realm" ], AnimalLocationFlag.main_path),
    "worm_big": AnimalLocation(112082, [ "Jättimato", "Giant Worm" ], [ "Mines", "Collapsed Mines", "Coal Pits", "Fungal Caverns", "Snowy Depths", "Underground Jungle", "Meat Realm" ], AnimalLocationFlag.reasonable),
    "worm_skull": AnimalLocation(112083, [ "Kalmamato", "Death Worm" ], [ "Temple of the Art", "The Work (Sky)" ], AnimalLocationFlag.main_path),
    "worm_end": AnimalLocation(112084, [ "Helvetinmato", "Hell Worm" ], [ "The Work (Hell)" ], AnimalLocationFlag.pain),
    "drone_physics": AnimalLocation(112085, [ "Lennokki", "Drone" ], [ "Fungal Caverns", "The Vault", "Frozen Vault", "The Tower" ], AnimalLocationFlag.main_path),
    "drone_lasership": AnimalLocation(112086, [ "Jättilaser-lennokki", "Giant Laser-Drone" ], [ "Hiisi Base", "The Vault", "Frozen Vault", "Power Plant" ], AnimalLocationFlag.main_path),
    "drone_shield": AnimalLocation(112087, [ "Turvalennokki", "Safety Drone" ], [ "Frozen Vault", "The Tower", "Power Plant", "Lukki Lair" ], AnimalLocationFlag.side_path),
    "basebot_sentry": AnimalLocation(112088, [ "Tarkkailija", "Observer" ], [ "Power Plant" ], AnimalLocationFlag.pain),
    "basebot_hidden": AnimalLocation(112089, [ "Vakoilija", "Spy" ], [ "Power Plant" ], AnimalLocationFlag.pain),
    "basebot_neutralizer": AnimalLocation(112090, [ "Pysäyttäjä", "Stopper" ], [ "Power Plant" ], AnimalLocationFlag.pain),
    "basebot_soldier": AnimalLocation(112091, [ "Teloittaja", "Executioner" ], [ "Power Plant" ], AnimalLocationFlag.pain),
    "healerdrone_physics": AnimalLocation(112092, [ "Korjauslennokki", "Repair Drone" ], [ "The Vault", "Frozen Vault", "Power Plant", "The Tower" ], AnimalLocationFlag.reasonable),
    "roboguard": AnimalLocation(112093, [ "Robottikyttä", "Robo-Cop" ], [ "Fungal Caverns", "The Vault", "Frozen Vault", "The Tower" ], AnimalLocationFlag.main_path),
    "roboguard_big": AnimalLocation(112094, [ "Kyrmyniska", "Hunchback" ], [ "Power Plant" ], AnimalLocationFlag.pain),
    "assassin": AnimalLocation(112095, [ "Salamurhaajarobotti", "Assassin Robot" ], [ "The Vault", "Frozen Vault", "Fungal Caverns", "The Tower" ], AnimalLocationFlag.main_path),
    "spearbot": AnimalLocation(112096, [ "Peitsivartija", "Lance Sentry" ], [ "Underground Jungle", "The Vault", "Frozen Vault", "The Sky", "The Work (Sky)", "The Tower" ], AnimalLocationFlag.main_path),
    "tank": AnimalLocation(112097, [ "KK-Tankki", "Tank" ], [ "Snowy Depths", "Hiisi Base", "The Vault", "Frozen Vault", "Desert Chasm", "Snowy Chasm", "The Tower" ], AnimalLocationFlag.main_path),
    "tank_rocket": AnimalLocation(112098, [ "IT-Tankki", "Rocket Tank" ], [ "Snowy Depths", "Hiisi Base", "Sandcave", "Frozen Vault", "The Tower" ], AnimalLocationFlag.main_path),
    "tank_super": AnimalLocation(112099, [ "Laser-Tankki", "Laser Tank" ], [ "Snowy Depths", "Hiisi Base", "The Vault", "Frozen Vault", "Power Plant", "The Tower" ], AnimalLocationFlag.main_path),
    "turret_left": AnimalLocation(112100, [ "Torjuntalaite", "Turret" ], [ "Hiisi Base", "The Vault", "Frozen Vault", "Power Plant", "The Tower" ], AnimalLocationFlag.never),
    "turret_right": AnimalLocation(112101, [ "Torjuntalaite", "Turret" ], [ "Hiisi Base", "The Vault", "Frozen Vault", "Power Plant", "The Tower" ], AnimalLocationFlag.main_path),
    "monk": AnimalLocation(112102, [ "Munkki", "Monk" ], [ "Snowy Depths", "Underground Jungle", "The Vault", "The Tower" ], AnimalLocationFlag.main_path),
    "missilecrab": AnimalLocation(112103, [ "Heinäsirkka", "Cricket" ], [ "The Vault", "Frozen Vault", "The Tower" ], AnimalLocationFlag.main_path),
    "necrobot": AnimalLocation(112104, [ "Tuonelankone", "Necrobot" ], [ "Frozen Vault", "The Tower", "Power Plant", "Meat Realm" ], AnimalLocationFlag.reasonable),
    "necrobot_super": AnimalLocation(112105, [ "Marraskone", "Super Necrobot" ], [ "Frozen Vault", "Power Plant", "Meat Realm" ], AnimalLocationFlag.pain),
    "fireskull": AnimalLocation(112106, [ "Liekkiö", "Fire Spirit" ], [ "Mines", "Coal Pits", "The Tower" ], AnimalLocationFlag.main_path),
    "iceskull": AnimalLocation(112107, [ "Jäätiö", "Ice Spirit" ], [ "Snowy Depths", "Snowy Chasm", "The Tower" ], AnimalLocationFlag.main_path),
    "thunderskull": AnimalLocation(112108, [ "Sähkiö", "Thunder Spirit" ], [ "Pyramid", "Snowy Depths", "Underground Jungle", "The Vault", "Snowy Chasm", "The Work (Hell)", "The Work (Sky)", "The Tower" ], AnimalLocationFlag.main_path),
    "firemage_weak": AnimalLocation(112109, [ "Stendari", "Fire Mage" ], [ "Mines", "Collapsed Mines", "Desert Chasm" ], AnimalLocationFlag.main_path),
    "firemage": AnimalLocation(112110, [ "Eldari", "Hellfire Mage" ], [ "Fungal Caverns", "The Vault", "Wizards' Den", "Frozen Vault", "Desert Chasm", "The Tower" ], AnimalLocationFlag.main_path),
    "icemage": AnimalLocation(112111, [ "Pakkasukko", "Old Man Winter" ], [ "Snowy Depths", "Frozen Vault", "Wizards' Den", "Snowy Chasm", "Snowy Wasteland", "The Tower" ], AnimalLocationFlag.main_path),
    "thundermage": AnimalLocation(112112, [ "Ukko", "Thunder Mage" ], [ "Fungal Caverns", "Snowy Depths", "The Vault", "Frozen Vault", "Wizards' Den", "The Sky", "Snowy Chasm", "Mines", "Desert Chasm", "The Tower" ], AnimalLocationFlag.main_path),
    "thundermage_big": AnimalLocation(112113, [ "Suur-Ukko", "Great Thunder Mage" ], [ "The Sky", "The Work (Sky)", "Pyramid", "Frozen Vault", "Snowy Chasm", "The Tower" ], AnimalLocationFlag.reasonable),
    "barfer": AnimalLocation(112114, [ "Turvonnu velho", "Bloated Wizard" ], [ "Temple of the Art", "Wizards' Den", "The Tower" ], AnimalLocationFlag.main_path),
    "wizard_dark": AnimalLocation(112115, [ "Sokaisunmestari", "Master of Blinding" ], [ "Fungal Caverns", "Snowy Depths", "The Vault", "Temple of the Art", "Wizards' Den", "Desert Chasm", "The Tower", "Lukki Lair" ], AnimalLocationFlag.main_path),
    "wizard_tele": AnimalLocation(112116, [ "Siirtäjämestari", "Master of Teleportation" ], [ "Fungal Caverns", "Snowy Depths", "Temple of the Art", "Wizards' Den", "The Work (Sky)", "The Sky", "Desert Chasm", "The Tower" ], AnimalLocationFlag.main_path),
    "wizard_poly": AnimalLocation(112117, [ "Muodonmuutosmestari", "Master of Polymorphing" ], [ "Fungal Caverns", "Temple of the Art", "Wizards' Den", "The Tower" ], AnimalLocationFlag.reasonable),
    "wizard_swapper": AnimalLocation(112118, [ "Vaihdosmestari", "Master of Exchange" ], [ "Fungal Caverns", "Snowy Depths", "Temple of the Art", "Wizards' Den", "The Sky", "The Tower" ], AnimalLocationFlag.main_path),
    "wizard_neutral": AnimalLocation(112119, [ "Maadoittajamestari", "Master of Grounding" ], [ "Ancient Laboratory", "Magical Temple", "The Vault", "Temple of the Art", "Pyramid", "Wizards' Den", "Snowy Depths", "The Tower" ], AnimalLocationFlag.main_path),
    "wizard_returner": AnimalLocation(112120, [ "Palauttajamestari", "Master of Returning" ], [ "Ancient Laboratory", "Magical Temple", "Temple of the Art", "Wizards' Den", "Desert Chasm", "The Tower" ], AnimalLocationFlag.main_path),
    "wizard_hearty": AnimalLocation(112121, [ "Haavoittajamestari", "Master of Wounding" ], [ "Underground Jungle", "Magical Temple", "The Vault", "Temple of the Art", "The Tower", "Pyramid", "Frozen Vault", "Wizards' Den", "Meat Realm", "Lukki Lair" ], AnimalLocationFlag.main_path),
    "wizard_homing": AnimalLocation(112122, [ "Kohdennusmestari", "Master of Homing" ], [ "The Tower", "Wizards' Den", "Lukki Lair" ], AnimalLocationFlag.side_path),
    "wizard_weaken": AnimalLocation(112123, [ "Turvattomuusmestari", "Master of Vulnerability" ], [ "Desert Chasm", "The Tower", "Pyramid", "Frozen Vault", "The Sky", "Wizards' Den", "Lukki Lair" ], AnimalLocationFlag.side_path),
    "wizard_twitchy": AnimalLocation(112124, [ "Sätkymestari", "Master of Twitching" ], [ "Fungal Caverns", "Underground Jungle", "Magical Temple", "The Vault", "Temple of the Art", "Pyramid", "Wizards' Den", "The Tower", "Lukki Lair" ], AnimalLocationFlag.main_path),
    "enlightened_alchemist": AnimalLocation(112125, [ "Valaistunut alkemisti", "Enlightened Alchemist" ], [ "Ancient Laboratory", "Magical Temple", "Temple of the Art", "Desert Chasm", "The Tower" ], AnimalLocationFlag.main_path),
    "failed_alchemist": AnimalLocation(112126, [ "Kadotettu alkemisti", "Damned Alchemist" ], [ "Ancient Laboratory", "Magical Temple", "Temple of the Art", "Wizards' Den", "Meat Realm", "The Tower" ], AnimalLocationFlag.main_path),
    "failed_alchemist_b": AnimalLocation(112127, [ "Epäalkemisti", "Non-alchemist" ], [ "Ancient Laboratory", "Magical Temple", "Temple of the Art", "The Tower" ], AnimalLocationFlag.main_path),
    "wraith": AnimalLocation(112128, [ "Hyypiö", "Creep" ], [ "Temple of the Art", "The Tower", "The Work (Hell)", "The Sky" ], AnimalLocationFlag.main_path),
    "wraith_storm": AnimalLocation(112129, [ "Ukkoshyypiö", "Thunder Creep" ], [ "The Tower", "The Sky", "The Work (Sky)" ], AnimalLocationFlag.pain),
    "wraith_glowing": AnimalLocation(112130, [ "Hohtava hyypiö", "Glowing Creep" ], [ "Magical Temple", "Temple of the Art", "The Sky", "The Work (Hell)", "The Tower", "The Work (Sky)" ], AnimalLocationFlag.main_path),
    "statue": AnimalLocation(112131, [ "Patsas", "Statue" ], [ "Ancient Laboratory", "The Tower" ], AnimalLocationFlag.side_path),
    "statue_physics": AnimalLocation(112132, [ "Hohtonaamio", "Glowing Mask" ], [ "Magical Temple", "The Tower" ], AnimalLocationFlag.main_path),
    "snowcrystal": AnimalLocation(112133, [ "Haamukivi", "Ghost Crystal" ], [ "Snowy Chasm", "The Tower" ], AnimalLocationFlag.reasonable),
    "hpcrystal": AnimalLocation(112134, [ "Elvytyskristalli", "Recovery Crystal" ], [ "Snowy Chasm", "Desert Chasm", "The Tower" ], AnimalLocationFlag.reasonable),
    "ghost": AnimalLocation(112135, [ "Houre", "Delirium" ], [ "Temple of the Art", "Wizards' Den", "Snowy Chasm" ], AnimalLocationFlag.main_path),
    "wand_ghost": AnimalLocation(112136, [ "Taikasauva", "Magic Wand" ], [ "Magical Temple" ], AnimalLocationFlag.side_path),
    "ethereal_being": AnimalLocation(112137, [ "Olematon", "Non-existent" ], [ "Snowy Chasm", "Pyramid" ], AnimalLocationFlag.reasonable),
    "playerghost": AnimalLocation(112138, [ "Kummitus", "Ghost" ], [ "Mines", "Collapsed Mines", "Coal Pits", "Fungal Caverns", "Snowy Depths", "Underground Jungle", "The Vault", "Temple of the Art", "Frozen Vault", "Lukki Lair", "Wizards' Den", "Overgrown Cavern", "Power Plant" ], AnimalLocationFlag.never),
    "phantom_a": AnimalLocation(112139, [ "Spiraalikalma", "Spiral Phantom" ], [ "Pyramid", "Magical Temple", "Temple of the Art", "Snowy Chasm", "The Tower" ], AnimalLocationFlag.side_path),
    "phantom_b": AnimalLocation(112140, [ "Kiukkukalma", "Angry Phantom" ], [ "Pyramid", "Magical Temple", "Temple of the Art", "Snowy Chasm", "The Tower" ], AnimalLocationFlag.side_path),
    "confusespirit": AnimalLocation(112141, [ "Utu-Aave", "Fog Spirit" ], [ "Fungal Caverns", "Overgrown Cavern", "Pyramid" ], AnimalLocationFlag.reasonable),
    "berserkspirit": AnimalLocation(112142, [ "Viha-Aave", "Anger Spirit" ], [ "Overgrown Cavern", "Pyramid" ], AnimalLocationFlag.reasonable),
    "weakspirit": AnimalLocation(112143, [ "Kaamo-Aave", "Depression Spirit" ], [ "Pyramid" ], AnimalLocationFlag.reasonable),
    "slimespirit": AnimalLocation(112144, [ "Neva-Aave", "Bog Spirit" ], [ "Coal Pits", "Fungal Caverns", "Meat Realm" ], AnimalLocationFlag.reasonable),
    "necromancer": AnimalLocation(112145, [ "Hahmonvaihtaja", "Shapechanger" ], [ "Magical Temple", "Temple of the Art", "Snowy Depths", "The Tower" ], AnimalLocationFlag.main_path),
    "gazer": AnimalLocation(112146, [ "Helvetinkatse", "Hell Gazer" ], [ "The Work (Hell)", "The Tower" ], AnimalLocationFlag.pain),
    "skygazer": AnimalLocation(112147, [ "Taivaankatse", "Sky Gazer" ], [ "The Work (Sky)" ], AnimalLocationFlag.pain),
    "spitmonster": AnimalLocation(112148, [ "Helvetin sylkijä", "Hell Spitter" ], [ "The Work (Hell)", "The Tower" ], AnimalLocationFlag.pain),
    "crystal_physics": AnimalLocation(112149, [ "Kirottu kristalli", "Cursed Crystal" ], [ "Temple of the Art", "The Tower" ], AnimalLocationFlag.main_path),
    "bloodcrystal_physics": AnimalLocation(112150, [ "Verikristalli", "Blood Crystal" ], [ "The Work (Hell)", "Meat Realm", "The Tower" ], AnimalLocationFlag.pain),
    "skycrystal_physics": AnimalLocation(112151, [ "Taivaskristalli", "Celestial Crystal" ], [ "The Tower", "The Sky", "The Work (Sky)" ], AnimalLocationFlag.pain),
    "chest_mimic": AnimalLocation(112152, [ "Matkija", "Mimic" ], [ "The Sky" ], AnimalLocationFlag.pain),
    "chest_leggy": AnimalLocation(112153, [ "Jalkamatkatavara", "Leggy Mimic" ], [ "The Sky" ], AnimalLocationFlag.never),
    "miner_hell": AnimalLocation(112154, [ "Hornantappurahiisi", "Hell Miner Hiisi" ], [ "Meat Realm" ], AnimalLocationFlag.pain),
    "shotgunner_hell": AnimalLocation(112155, [ "Hornahiisi", "Hell Shotgun Hiisi" ], [ "Meat Realm" ], AnimalLocationFlag.pain),
    "sniper_hell": AnimalLocation(112156, [ "Hornasnipuhiisi", "Hiisi Hell Sniper" ], [ "Meat Realm" ], AnimalLocationFlag.pain),
    "dark_alchemist": AnimalLocation(112157, [ "Pahan muisto", "Memory of Evil" ], [ "The Sky" ], AnimalLocationFlag.never),
    "shaman_wind": AnimalLocation(112158, [ "Valhe", "Lie" ], [ "The Sky" ], AnimalLocationFlag.never),
    "necromancer_shop": AnimalLocation(112159, [ "Stevari", "Guard" ], [ "Snowy Depths", "The Tower" ], AnimalLocationFlag.reasonable),
    "necromancer_super": AnimalLocation(112160, [ "Skoude", "Cop" ], [ "Snowy Depths", "The Tower" ], AnimalLocationFlag.reasonable),
    "boss_dragon": AnimalLocation(112161, [ "Suomuhauki", "Dragon" ], [ "Underground Jungle" ], AnimalLocationFlag.never ),
    "boss_limbs": AnimalLocation(112162, [ "Kolmisilmän Koipi", "Three-Eye's Legs" ], [ "Pyramid" ], AnimalLocationFlag.never ),
    "boss_meat": AnimalLocation(112163, [ "Kolmisilmän sydän", "Three-Eye's Heart" ], [ "Meat Realm" ], AnimalLocationFlag.never ),
    "boss_alchemist": AnimalLocation(112164, [ "Ylialkemisti", "High Alchemist" ], [ "Ancient Laboratory" ], AnimalLocationFlag.never ),
    "parallel_alchemist": AnimalLocation(112165, [ "Alkemistin Varjo", "Alchemist's Shadow" ], [ "Parallel Worlds" ], AnimalLocationFlag.pain ),
    "boss_ghost": AnimalLocation(112166, [ "Unohdettu", "Forgotten" ], [ "Snowy Chasm" ], AnimalLocationFlag.never ),
    "boss_ghost_polyp": AnimalLocation(112167, [ "Häive", "Fade" ], [ "Snowy Chasm" ], AnimalLocationFlag.never ),
    "islandspirit": AnimalLocation(112168, [ "Tapion vasalli", "Tapio's Vassal" ], [ "Lake" ], AnimalLocationFlag.never ),
    "boss_pit": AnimalLocation(112169, [ "Sauvojen tuntija", "Connoisseur of Wands" ], [ "Abyss Orb Room" ], AnimalLocationFlag.never ),
    "boss_robot": AnimalLocation(112170, [ "Kolmisilmän silmä", "Three-Eye's Eye" ], [ "Power Plant" ], AnimalLocationFlag.never ),
    "fish_giga": AnimalLocation(112171, [ "Syväolento", "Creature of the Deep" ], [ "Lake" ], AnimalLocationFlag.never ),
    "maggot_tiny": AnimalLocation(112172, [ "Limatoukka", "Slime Maggot" ], [ "Meat Realm" ], AnimalLocationFlag.never ),
    "parallel_tentacles": AnimalLocation(112173, [ "Kolmisilmän Kätyri", "Three-eye's Minion" ], [ "Parallel Worlds" ], AnimalLocationFlag.pain ),
    "minipit": AnimalLocation(112174, [ "Pienkätyri", "Tiny Minion" ], [ "Frozen Vault", "The Tower", "Power Plant", "Meat Realm" ], AnimalLocationFlag.pain ),
    "gate_monster_a": AnimalLocation(112175, [ "Veska", "Goalkeeper" ], [ "Temple of the Art" ], AnimalLocationFlag.never ),
    "gate_monster_b": AnimalLocation(112176, [ "Molari", "Goalkeeper" ], [ "Temple of the Art" ], AnimalLocationFlag.never ),
    "gate_monster_c": AnimalLocation(112177, [ "Mokke", "Goalkeeper" ], [ "Temple of the Art" ], AnimalLocationFlag.never ),
    "gate_monster_d": AnimalLocation(112178, [ "Seula", "Sieve" ], [ "Temple of the Art" ] , AnimalLocationFlag.never),
    "boss_wizard": AnimalLocation(112179, [ "Mestarien mestari", "Master of Masters" ], [ "Wizards' Den" ], AnimalLocationFlag.never ),
    "boss_centipede": AnimalLocation(112180, [ "Kolmisilmä", "Three-Eye" ], [ "The Laboratory" ], AnimalLocationFlag.never ),
    "ultimate_killer": AnimalLocation(112181, [ "Kauhuhirviö", "Horror Monster" ], [ "Frozen Vault", "Friend Cave" ], AnimalLocationFlag.never ),
    "friend": AnimalLocation(112182, [ "Toveri", "Friend" ], [ "Friend Cave" ], AnimalLocationFlag.never ),
    "boss_sky": AnimalLocation(112183, [ "Kivi", "Stone" ], [ "The Sky" ], AnimalLocationFlag.never ),
    "darkghost": AnimalLocation(112184, [ "Haamu", "Wraith" ], [ "Forest" ], AnimalLocationFlag.never ),
    "meatmaggot": AnimalLocation(112185, [ "Mätäryömijä", "Putrid Crawler" ], [ "Meat Realm" ], AnimalLocationFlag.pain )
}